### ISSUE TITLE
Small delay when switching apps?

### ISSUE THREAD

**Issue by Fraedon** [pigigaldi/Pock#10]
There seems to be a minor delay in the UI's appearance refreshing whenever an app is switched. Not super annoying or anything, but just thought it should be mentioned.

**Comment by Somnus13** [comment]
same as u

> There seems to be a minor delay in the UI's appearance refreshing whenever an app is switched. Not super annoying or anything, but just thought it should be mentioned.

**Comment by pigigaldi** [comment]
I'm closing this. Feel free to re-open this if you're still facing this issue with the latest release (https://pock.dev)
