### ISSUE TITLE
Time Format in Status Widget

### ISSUE THREAD

**Issue by scarysnow** [pigigaldi/Pock#100]
The time within the status widget is not formatted according to system preferences and appears to default to a 24-hour clock only. Would prefer if the widget respected the system preferences for displaying the time and date.

**Comment by iDjay** [comment]
It‘s also not updating in my case 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by AjitZero** [comment]
Time still does not update properly at times. I'm still trying to reproduce this. Right now while I'm writing this the time is an hour and a half behind, while earlier today it was fine. Yesterday it was only 10 minutes behind, so I've no idea what's causing this.

**Comment by pigigaldi** [comment]
#184
