### ISSUE TITLE
Add play/pause button as alternative to pulsating Spotify icon

### ISSUE THREAD

**Issue by BLamy** [pigigaldi/Pock#101]
**Is your feature request related to a problem? Please describe.**
I find the pulsating now playing spotify icon to be a little distracting. 

**Describe the solution you'd like**
I would prefer to just have a standard play/pause button widget if possible. 

**Describe alternatives you've considered**
Not complaining about tiny things. 

**Additional context**
Really like the new update.

**Comment by dotarmin** [comment]
> I find the pulsating now playing spotify icon to be a little distracting.

I noticed this today actually and can just agree on the distraction factor. For me it would also work well with just having a non pulsating Spotify icon.

@pigigaldi, thanks for this amazing project!

**Comment by pigigaldi** [comment]
An option to disable pulsating icon was added in the latest release: [0.7.1](https://github.com/pigigaldi/Pock/releases/tag/0.7.1)
