### ISSUE TITLE
Pock doesn‘t save „launch at Login“ Option

### ISSUE THREAD

**Issue by iDjay** [pigigaldi/Pock#102]
Same reason for #98 Issue.
1. Check „launch at login“ 
2. restart
3. Pock doesn‘t launch
4. Option is not checked

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by jebrii** [comment]
I am also experiencing this issue.

**Comment by XternA** [comment]
> I am also experiencing this issue.

Manually add the application to your startup entry in User login items and it'll work. Albeit in the Pock app it will be unticked.

**Comment by jebrii** [comment]
> > I am also experiencing this issue.
> 
> Manually add the application to your startup entry in User login items and it'll work. Albeit in the Pock app it will be unticked.

I'm able to do this in **System Preferences > Users & Groups > [my-user] > Login Items** (for future reference to other users.

Needless to say, one should still keep this Issue open until the "Launch at Login" button does as advertised.

**Comment by Teragion** [comment]
Try moving `Pock.app` into your `Application` folder.

**Comment by MateuszDabrowski** [comment]
@Teragion Moving changes nothing - it does remember all preferences settings but this one.
@pigigaldi Unfortunately the newest version (0.5.3) does not fix that issue.

**Comment by mikfoo** [comment]
I've got the same issue, and I can reproduce it by simply toggling it on, quitting Pock, opening it again, and then it's toggled off again.

I'm on 0.5.3 and previous versions were affected as well. Let me know if there's anything I can do to help debugging this issue.

**Comment by lawbokent** [comment]
same for my MacBook Pro 2018, I checked the "launch at login" option but every time I quit the app and relaunch it, the check box returns to blank
I am currently using pock version 0.5.3

**Comment by XternA** [comment]
@lawbokent It isn't fixed yet and will continue to be the case for the time being. Just following @jebrii instructions which expanded from mine and you'll be fine for now.
