### ISSUE TITLE
Opening the home folder from finder strip fails

### ISSUE THREAD

**Issue by TechieGenie** [pigigaldi/Pock#103]
When I press `Open` Button from Pock's finder screen in the home directory, finder doesn't open and shows below message. Every other directory opens fine.

![pock_finder_launch_fail](https://i.ibb.co/7W6LVpN/Screenshot-2019-06-25-at-3-49-58-PM.png)

**Comment by MateuszDabrowski** [comment]
Same here - happens only for home directory and only when preferences are set up to open folders within pock and when I click "Open" on the home directory. Other paths with these preferences work fine. If I change preferences to open folders directly in finder, clicking finder icon opens the home directory without any problem.
