### ISSUE TITLE
Close button converting to ESC 

### ISSUE THREAD

**Issue by DefCon-007** [pigigaldi/Pock#109]
**Describe the bug**
Two ESC buttons are shown on touch bar when on Pock preference window. 

**To Reproduce**
1. Go to Pock > Preferences
2. Look at the pock on touch bar, the close button converts into ESC

**Expected behavior**
Close button should remain  as it is. 

**Screenshots**
<img width="1085" alt="Touch Bar Shot 2019-06-25 at 11 31 25 PM" src="https://user-images.githubusercontent.com/16754547/60122094-1ab3d500-97a2-11e9-859b-3e007094c276.png">

**Desktop (please complete the following information):**
 - OS: Mac OS 10.14.5
 - Version 0.5.1

**Comment by rdelval** [comment]
https://github.com/pigigaldi/Pock/issues/94
