### ISSUE TITLE
No 'Now Playing' Widget Icon

### ISSUE THREAD

**Issue by tommyboylab** [pigigaldi/Pock#111]
#### The Now Playing widget is missing album art or an icon - Appears as a white page placeholder

**To Reproduce**
1. Go to customize in the menu bar
2. Add the Now Playing widget to the Pock Touchbar
3. Play a song through Apple Music, or watch something on Chrome
4. See the missing icon, placeholder 

Either the focused apps Icon or the Album art for the currently playing song should be present

**Screenshots**
![image](https://user-images.githubusercontent.com/44362297/60181535-b1c07180-9822-11e9-8824-2994f2349c1d.png)

**Desktop (please complete the following information):**
 - OS: Mac OS 10.15 Beta
 - Browser: Chrome,
 - Music Player: Apple Music,
 - Version: 0.5.1

**Additional context**
Could possibly be due to the transition from iTunes to Apple Music

**Comment by L1cardo** [comment]
This has been fixed. #134
Since the Apple replaced iTunes with Music app, there is no iTunes any more so that Pock can’t show iTunes icon.
This has been fixed. Just wait for a new release.

**Comment by tommyboylab** [comment]
Confirmed working. Pock icon is showing in the Menubar.
