### ISSUE TITLE
How to build locally?

### ISSUE THREAD

**Issue by mikew** [pigigaldi/Pock#112]
I'd like to try and implement https://github.com/pigigaldi/Pock/issues/22, but am unsure how to get this project building in XCode.

What I've done so far:

```sh
brew install cocoapods
pod setup
git clone https://github.com/pigigaldi/Pock.git
pod install
```

But that's where it fails, since the `Podfile` references `../Pod/PockKit/`, which doesn't exist anywhere.

Commenting out that line allows `pod install` to work, but then a build will fail on the files that `import PockKit`.

**Comment by pigigaldi** [comment]
I'm going to publish `PockKit` on CocoaPods in few hours so you can compile the project and continue with your implementation.
Documentation on how to use `PockKit` will be available later.
Thanks!

**Comment by pigigaldi** [comment]
`PockKit [0.1.1]` is now available on CocoaPods!
https://github.com/CocoaPods/Specs/commit/888c0e8e81fb79bb8449f2b1bc8c8a3c90668333

Please, pull changes and have fun with your implementation! 🏄‍♂️
