### ISSUE TITLE
Long press on dock icons triggers app exposé

### ISSUE THREAD

**Issue by EugenioMoro** [pigigaldi/Pock#113]
**Is your feature request related to a problem? Please describe.**
With apps such as preview, there are often many windows opened at once and in pock there's no way to open a specific one.

**Describe the solution you'd like**
When long pressing on an icon, app exposé should open.

**Describe alternatives you've considered**
I don't think there's any other valid alternative to trigger app exposé

**Comment by pigigaldi** [comment]
App Exposé feature is available from version 0.6 🎉
