### ISSUE TITLE
Calendar icon doesn't update

### ISSUE THREAD

**Issue by kopf** [pigigaldi/Pock#119]
**Describe the bug**
The icon for the OS X Calendar updates in the dock to show the current date (e.g. "Jul 1"). This does not happen in pock.

**To Reproduce**
* Add Calendar to the dock
* Run pock
* Wait a day
* Observe that the icon in the dock has been updated to the current date, but in pock it's displaying yesterday's date

**Expected behavior**
The Calendar icon in pock should be up-to-date

**Additional context**
Possibly related to #90

**Comment by pigigaldi** [comment]
Nope, this is not related to #90; it just picks the Calendar app default icon.
I still need to figure this out.

**Comment by mbauman** [comment]
Duplicate of #36.
