### ISSUE TITLE
Double tap `ctrl` doesn't toggle control strip

### ISSUE THREAD

**Issue by geekdada** [pigigaldi/Pock#123]
**Describe the bug**
I have selected "hide control strip", but double tapping `ctrl` simply has no effect. I have tried to find whether if there is any conflict app, but I failed.

**To Reproduce**
null

**Expected behavior**
Eh, toggle control strip

**Desktop (please complete the following information):**
 - OS: 10.14.5

**Additional context**
- I have Karabiner installed, but it seems not the problem.
- No suspicious logs found.

**Comment by MateuszDabrowski** [comment]
This will be a stupid question, but have you @geekdada tried quitting pock and relaunching it? Double control was not working for me either before restarting the Pock. Now it works flawlessly.

**Comment by DominicHolmes** [comment]
Same for me @MateuszDabrowski -- thanks!

**Comment by geekdada** [comment]
@MateuszDabrowski Awesome!

**Comment by ronivay** [comment]
Same issue here. This worked fine when i launched the app first time and messed around with the settings. After tweaking the touchbar content with now playing widget etc, this doesn't work anymore. Tried relaunching the app couple of times, toggle "hide control strip" on/off, deleted widgets and so on but nothing helps.

**Comment by ganey** [comment]
Quitting and re-opening Pock fixed this for me 👍

**Comment by jellycsc** [comment]
@MateuszDabrowski Thanks!

**Comment by pigigaldi** [comment]
Thanks @MateuszDabrowski 
Closing but if you face this issue again, please feel free to re-open.
