### ISSUE TITLE
Hide the Now Playing widget when it's not in use

### ISSUE THREAD

**Issue by bafulton** [pigigaldi/Pock#127]
I'd love for the Now Playing widget to only show up when I'm actually playing something. When nothing is playing, it's just wasting valuable touch bar real estate.

**Comment by DominicHolmes** [comment]
This is a good option to have, but I love starting my music with the widget

**Comment by pigigaldi** [comment]
Maybe an option to toggle between both solutions? 👀

**Comment by pigigaldi** [comment]
Option to hide widget when nothing is playing was added in the latest release: [0.7.1](https://github.com/pigigaldi/Pock/releases/tag/0.7.1)
