### ISSUE TITLE
Add volume and brightness sliders to Control Center widget

### ISSUE THREAD

**Issue by bafulton** [pigigaldi/Pock#128]
I'd love to see the Control Center widget have an option for volume and brightness sliders, instead of the current up/down buttons.

**Comment by pigigaldi** [comment]
Long press or slide on control center item to invoke sliders 🏄🏻

**Comment by jberglinds** [comment]
Hi @pigigaldi. Is it possible to make the buttons behave as the native ones on slide? 
If you slide the native buttons for brightness or volume the slider handle is already grabbed so you can do it in one motion. With Pock, the slider activates on the first slide, and then I need to remove and put my finger back on the handle to actually adjust. See this article for some gifs on how it works natively: https://www.howtogeek.com/305066/how-to-adjust-volume-and-brightness-in-one-gesture-on-the-macbook-pro-touch-bar/

Maybe not currently possible?
Thank you for Pock!
