### ISSUE TITLE
Custom control strip

### ISSUE THREAD

**Issue by gnachman** [pigigaldi/Pock#129]
**Is your feature request related to a problem? Please describe.**
There are two things I need from the touch bar: the esc key in its usual place and the control strip. I'd also like to move the dock into it to save some space on the screen, but doing so causes the (X) button to be added on the left, moving the esc key. I can't live with that.

**Describe the solution you'd like**
Since the OS adds that button when the control strip is present, one solution to my problem would be to replace the system's control strip with a custom one that does the same thing (at least volume and brightness).

**Describe alternatives you've considered**
You could try to hack around it with private APIs but it would be painful to support.

**Comment by pigigaldi** [comment]
Pock 0.5 has a built-in widget that shows Volume and Brightness buttons. Long press or swipe on one of those buttons will invoke the slider control.
