### ISSUE TITLE
Only show date

### ISSUE THREAD

**Issue by sebastiaanspeck** [pigigaldi/Pock#132]
Maybe it is a nice feature to toggle if you want to show the time, since the time is frozen quite often.

**Comment by L1cardo** [comment]
Yeah , I want to toggle my date too.
I just want to show time without month or week.
And it will be better that we can switch 12h between 24h format.

**Comment by L1cardo** [comment]
> Maybe it is a nice feature to toggle if you want to show the time, since the time is frozen quite often.

This has been added to the latest version, please have a look !

**Comment by pigigaldi** [comment]
This was implemented by @L1cardo 🙏
