### ISSUE TITLE
can't bring pock back

### ISSUE THREAD

**Issue by thomasd3** [pigigaldi/Pock#136]
when I clock on the 'close' icon on the left, when the desktop is selected; pock goes away and there is an icon for it, on the right, next to the control strip.
clicking on this icon doesn't do anything and doesn't bring pock back.

**Comment by MateuszDabrowski** [comment]
This issue was already created: https://github.com/pigigaldi/Pock/issues/96
The short term solution is to quit Pock and relaunch it, which will make the pock icon working just right.
