### ISSUE TITLE
Is there a way to remove the X from the strip?

### ISSUE THREAD

**Issue by fwachs** [pigigaldi/Pock#138]
Is there a way to remove the X from the strip? I keep closing pock by mistake when trying to hit ESC instead.

**Comment by MacDragon** [comment]
If you hide the control strip then the x vanishes, but then need to switch back to native touchbar or add brightness/volume controls to get access to those.

**Comment by pigigaldi** [comment]
Unfortunately, not at the moment.
I need to investigate more about this.

**Comment by fwachs** [comment]
Any news regarding this?
