### ISSUE TITLE
Can't control media button 

### ISSUE THREAD

**Issue by nielsvr** [pigigaldi/Pock#14]
In the screenshot I see the media buttons on the right. When I launch Pock the right side is black. So I can't control the volume or brightness of my screen. Is that expected?
 
Mac Os 10.14.3 (18D109)

**Comment by pigigaldi** [comment]
Media buttons are from the system control strip. Maybe you have to uncheck the `Hide Control Strip` option from Pock preference pane.

**Comment by nielsvr** [comment]
Then I don’t see my dock on the touchbar...

**Comment by nielsvr** [comment]
Found out that the touch bar setting "Touch bar shows" need to be on program switches and show control strip should be toggled on... got confused there. Works now!

**Comment by travispamaral** [comment]
@nielsvr can you explain better what settings you set to get this to work? Currently `Hide Control Strip` locks Pock but nothing in System Settings will show media buttons or allow to switch to medium buttons

**Comment by nickatdivvy** [comment]
Figured this one out - You need to open Keyboard settings (https://www.idownloadblog.com/2019/02/27/customizing-touch-bar-function-keys-media-controls/), then set "Touch bar shows" to App controls. You also need to set the Pock settings to untoggle "Hide control strip". This will get you the dock + whatever default keys you want.

<img width="1412" alt="Screen Shot 2019-06-11 at 1 33 02 PM" src="https://user-images.githubusercontent.com/31252093/59823933-94504c80-92e4-11e9-9d90-92fd2f058d1c.png">
<img width="1412" alt="Screen Shot 2019-06-13 at 8 22 31 PM" src="https://user-images.githubusercontent.com/31252093/59823937-97e3d380-92e4-11e9-9fe4-eb130a8806a4.png">
