### ISSUE TITLE
Esc does nothing while app switching

### ISSUE THREAD

**Issue by pikeas** [pigigaldi/Pock#143]
OS X 10.14.5 // Pock 0.5.3

**Describe the bug**
When the application switcher has focus and Pock controls the dock (the bug goes away after double tapping ctrl to switch to the system Dock), the escape key does not work.

**To Reproduce**
Press cmd key, press tab at least once, press esc.

**Expected behavior**
App switcher should be canceled.

**Comment by pigigaldi** [comment]
This happens because the 3rd party app's Touch Bar has user interaction disabled in that situation.
You may face the same issue if you try to use the Touch Bar while in `Mission Control`.
