### ISSUE TITLE
[0.5.3] Safari doesn‘t open

### ISSUE THREAD

**Issue by iDjay** [pigigaldi/Pock#145]
After updating to 0.5.3 tapping on Safari won‘t open a new window.
Video:
https://we.tl/t-IwDSehE2Wm

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by MateuszDabrowski** [comment]
It's not just Safari - 0.5.3 stopped opening applications if they are hidden in the dock.

0.5.2 was either changing screen to the one with the app if it is already opened or opening the app in another case.
0.5.3 still does the first thing but is no longer opening the window of the app.

**Comment by josephsiu** [comment]
I came to report this as well. Hidden apps that are open on other desktops do not seem to open; this was working well in 0.5.2.

**Comment by josephsiu** [comment]
@iDjay Perhaps we should update this bug to be more general? Or are you only having the issue with Safari?

**Comment by pigigaldi** [comment]
This issue should be fixed now that App Exposé is fully released.
Feel free to re-open if you face this situation again.
