### ISSUE TITLE
Wrong function on Volume down

### ISSUE THREAD

**Issue by kalongo** [pigigaldi/Pock#151]
Hi,

When "Show Sleep item" is activated in Control Center Widget, a long press on Volume Down makes the light's slider appears instead of the volume's one.

Kalongo

**Comment by tomglenn** [comment]
Similarly, the wrong slider appears for me if I don't have both the brightness up/down and volume up/down (so, all 4) enabled.

If I only enable for example, lock, brightness up and volume up. 
Then the lock works, brightness up long press brings up volume slider, brightness up long press does nothing.

**Comment by PhilippeSch** [comment]
Same if only the lock is activated together with the brightness/sound, then the volume down is mapped to the brightness settings. Very strange that it works if lock and sleep are **not** activated...

**Comment by dotarmin** [comment]
+1

**Comment by litepoet** [comment]
Same problem when "show lock item".

**Comment by pigigaldi** [comment]
This should be fixed in the latest releases.
