### ISSUE TITLE
Brightness & Volume controls don't function as expected

### ISSUE THREAD

**Issue by hmgnsd** [pigigaldi/Pock#159]
**Describe the bug**
If I set the control panel widget to just be one brightness and one volume button, knowing that tap and hold should bring up the slider; tapping and holding on the volume button (next to Touch ID) does nothing and tapping and holding on the brightness button brings up the volume slider.

**How to reproduce**

1. Go to 'Preferences'
2. Click on 'Control Centre Widget'
3. Show Brightness and Volume items but only tick one, i.e. Brightness & Volume up, but not down
4. See error when tap and hold is attempted

**Expected behavior**
Should be able to tap on brightness button to summon brightness slider and the same for volume, regardless of whether all options are ticked?

**Crashlog**
Also crashes a lot

**Versions:**
 - macOS version: 10.14.5 (18F203)
 - Pock version: 0.5.3

[pock crash logs.zip](https://github.com/pigigaldi/Pock/files/3374341/pock.crash.logs.zip)

**Comment by lucien-guoheng** [comment]
There is a suggestion. One way is to cut the feature of displaying brightness or volume slider, caz it always mistake my operation, like, when I just wanna tap on it, it sometimes shows slider, and it seems that it would never fade if I don't tap on the cancel bottom.
The second way is to introduce the brightness and volume sliders directly. It would be more instinctive, and easier to use.

**Comment by lcukerd** [comment]
@pigigaldi This should have been fixed with my recent merge.

**Comment by pigigaldi** [comment]
#184
