### ISSUE TITLE
Pock Ribbon won't close while browsing finder

### ISSUE THREAD

**Issue by TechieGenie** [pigigaldi/Pock#162]
While browsing finder in `Pock`, I am presented with 2 close <kbd>x</kbd> buttons. One of the inner close buttons works like closing the finder browser. But the main close button is working as back button in finder, instead of closing the Pock Ribbon. While performing this task,  <kbd>Esc</kbd> button is also not visible.

**Comment by TechieGenie** [comment]
As a temporary fix, one can double press <kbd>Ctrl</kbd> and close the pock strip and double press again to resume browsing from same place.

**Comment by pigigaldi** [comment]
This is the expected behavior if the option "Hide Control Strip" is disabled.

**Comment by pigigaldi** [comment]
This is the expected behavior if the option "Hide Control Strip" is disabled.
