### ISSUE TITLE
Can not open the app window after closing the app window

### ISSUE THREAD

**Issue by Neooolee** [pigigaldi/Pock#164]
**Describe the bug**
A clear description of what the bug is.
When I touch the running app icon, it cannot open the app window after closing the running app window,
**How to reproduce**
```
1. Go to '...'
2. Click on '....'
3. Scroll to '....'
4. See error
```

**Expected behavior**
A clear description of what you expected to happen.

**Screenshots**
`To take a Touch Bar screenshot use the shortcut "shift + cmd + 6"`

**Crashlog**
If applicable, add crashlog to help me investigate your problem.
``` 
1. Open the Console application located at "Application -> Utilities -> Console.app."
2. Click on "User Reports" in the left menu, then locate the latest Pock crash report. (You can filter reports by typging "pock" into the searchbar on the top)
3. "ctrl + click" on the latest Pock crash report and click on "Reveal in Finder" option, then attach the .crash file in this issue.
```

**Versions:**
 - macOS version: [e.g. 10.14.5 (*required)]
 - Pock version:  [e.g. 0.5.2   (*required)]

**Additional context**

**Comment by pigigaldi** [comment]
https://github.com/pigigaldi/Pock/issues/174#issuecomment-514810602
