### ISSUE TITLE
[Request] Double click on "Now Playing" widget to change song

### ISSUE THREAD

**Issue by lucacorbucci** [pigigaldi/Pock#166]
Hi, i'm using the new "Now Playing" widget and i saw that with a single click i can play/pause the music. Is possible to add the possibility to go to the next song with a double tap?

Thank you!

**Comment by mynetx** [comment]
@lucacorbucci You can swipe the widget to the left to move to the previous song, or to the right to switch to the next song. Does that work for you?

**Comment by lucacorbucci** [comment]
> @lucacorbucci You can swipe the widget to the left to move to the previous song, or to the right to switch to the next song. Does that work for you?

Hi, yes i tried to swipe left or right but it doesn't work really well, only in some cases i'm able to go back to the start of the song and I'm never able to go to the next song.

**Comment by mynetx** [comment]
Hmm, for me that works – with Spotify.

**Comment by nova0052** [comment]
When listening to a song where the track title and artist are both short (i.e. 'Song 2' by Blur), the Spotify widget gets very small, making it difficult to swipe left/right.

I'm finding that trying to swipe up/down is more reliable for switching tracks than left/right

**Comment by lucacorbucci** [comment]
> When listening to a song where the track title and artist are both short (i.e. 'Song 2' by Blur), the Spotify widget gets very small, making it difficult to swipe left/right.

You're right, i've just tried a song with a longer title and the the left/right swipe works.

> 
> I'm finding that trying to swipe up/down is more reliable for switching tracks than left/right

Thank you, i haven't seen this gesture, this is better than the right/left swipe and moreover it works every time!

**Comment by DominicHolmes** [comment]
> I'm finding that trying to swipe up/down is more reliable for switching tracks than left/right

This should be in the docs / instructions! I have about a 20% hit rate with swiping left and right. But up/down works every time. Thanks for this!

**Comment by maxisvest** [comment]
> When listening to a song where the track title and artist are both short (i.e. 'Song 2' by Blur), the Spotify widget gets very small, making it difficult to swipe left/right.
> 
> I'm finding that trying to swipe up/down is more reliable for switching tracks than left/right

It's work when up and down!

**Comment by YemreGurses** [comment]
I think, double tap for the next song and triple tap fo the previous song option should be included too. 
Many people will want to use it like this. Because that's the way headphone buttons do as well.

**Comment by pigigaldi** [comment]
The latest version of Pock includes three different styles for the **Now Playing** widget. You can try switch to one of them to use *"physical"* buttons to skip back or forward through your songs.
