### ISSUE TITLE
How to launch?

### ISSUE THREAD

**Issue by pdog18** [pigigaldi/Pock#17]
> Last login: Wed Mar 27 13:31:29 on ttys000
 pdog@pdog  ~  git clone http://github.com/pigigaldi/Pock
Cloning into 'Pock'...
warning: redirecting to https://github.com/pigigaldi/Pock/
remote: Enumerating objects: 425, done.
remote: Counting objects: 100% (425/425), done.
remote: Compressing objects: 100% (237/237), done.
remote: Total 804 (delta 207), reused 395 (delta 178), pack-reused 379
Receiving objects: 100% (804/804), 1.84 MiB | 678.00 KiB/s, done.
Resolving deltas: 100% (367/367), done.
 pdog@pdog  ~  cd Pock/
 pdog@pdog  ~/Pock   master  pod install
Analyzing dependencies
Downloading dependencies
Installing Crashlytics (3.10.9)
Installing Defaults (1.0.0)
Installing Fabric (1.7.13)
Installing LaunchAtLogin (2.3.0)
Installing Magnet (2.3.0)
Installing Preferences (0.2.0)
Installing SnapKit (4.0.1)
Generating Pods project
Integrating client project
Sending stats
Pod installation complete! There are 7 dependencies from the Podfile and 7 total pods installed.
 pdog@pdog  ~/Pock   master ●  open Pock.xcworkspace

I just get a Finder window, Excuse me, how do I start it?

**Comment by pigigaldi** [comment]
You can download the compiled package at http://pock.pigigaldi.com
