### ISSUE TITLE
Launched App Do Not Open Window On Tap

### ISSUE THREAD

**Issue by josephsiu** [pigigaldi/Pock#174]
**Describe the bug**
When an app is launched but without any open windows, Pock will switch to the app on tap but will not open the primary window for the app. This is expected behavior from a dock action.

**How to reproduce**
```
1. Add Chrome to the dock and Pock
2. Launch Chrome (or any apps that do not quit when the last window is closed)
3. Close all Chrome windows but leave Chrome running
4. Use another application (have another app as focus)
5. Click on the Chrome icon in Pock touch bar
6. Chrome will be the app in focus in the menu, but no windows will open
```

**Expected behavior**
What should happen in step 6 above is that a new Chrome window should open. This is the default behavior if the same thing happens for an app and the app icon is clicked on in the dock.

**Versions:**
 - macOS version: 10.14.5
 - Pock version:  0.5.3

**Comment by lucien-guoheng** [comment]
I have the same issue. When the app is on but no windows active, tapping this app on Touch Bar shows nothing. Just like using (command + tab) to switch to a app without any windows, it seems that it don't creative a new window.

**Comment by benoitzohar** [comment]
Same issue here. I can reproduce with:
 - Slack
 - Calendar
 - and pretty much any app that can be open without displaying any window.

**Comment by pigigaldi** [comment]
This is a bug introduced with the initial multi-window support that is currently partially implemented.
I hope to publish a fully-functional release this weekend! 🤞

**Comment by robertdistefano** [comment]
Any progress on this one? Seems to be happening for me, too. Would love to replace my on-screen Dock with Pock moving forward! Thank you for the awesome project.

macOS 10.14.6
Pock 0.5.3

**Comment by elimuhub** [comment]
Bug

**Comment by elimuhub** [comment]
Bug

**Comment by tofixx** [comment]
would love to see a progress here, this affects all windows if i have closed them :)

**Comment by pigigaldi** [comment]
> This is a bug introduced with the initial multi-window support that is currently partially implemented.
> I hope to publish a fully-functional release this weekend! 🤞

I'm working on an update that is coming soon that will introduce multi-window support.
