### ISSUE TITLE
Control Center widget should have mute.

### ISSUE THREAD

**Issue by dalelarsen** [pigigaldi/Pock#175]
**Describe the feature you'd like to have in Pock**
Add mute button to the "Control Center "widget. It has volume up and volume down but no mute. I use mute way more often than changing the volume. Ideally, however, would be one button that mutes/unmutes when you touch it, and then long press and slide will adjust the volume. One volume button to rule them all.

**Describe alternatives you've considered**
An alternative is using the default system one instead of hiding it in favor of the pock one. But I would rather hide the control strip so I don't see the close button on the left next to the "esc" that I keep hitting. Another option is to use the double ctrl to quickly get to the default control strip which has mute.

**Comment by pigigaldi** [comment]
There is already an open PR (#172) that will be merged as soon as the author addresses some minor requested changes. 🎉
