### ISSUE TITLE
Dock doesn't get refresh when a window is minimized

### ISSUE THREAD

**Issue by TechieGenie** [pigigaldi/Pock#177]
I minimize a window by pressing <kbd>Cmd</kbd> <kbd>M</kbd> or by pressing the minimize control at the Menu an item in the dock increases, but `Pock` ribbon doesn't refresh with new item.

Not sure if that's the expected behavior or not. It would be good if the items show up in the dock.

**Comment by pigigaldi** [comment]
Pock doesn't support minimized windows in Dock right now. I still don't know if this will be added as a future request or not.
