### ISSUE TITLE
Switch the location of esc and close buttons

### ISSUE THREAD

**Issue by esfandiar** [pigigaldi/Pock#18]
First of all, this is an amazing tool, well done and thank you. I have a feature request. To me it makes more sense if the "Esc" button goes all the way to the left, and the "x" button goes to the right of it. So essentially "Esc" and "x" buttons are switched, like below:

esc ---- x ----- application icons ----- Other Touch Bar stuff

The reason, is that it's bit harder to hit the Esc button now without looking. Usually the Esc button goes all the way to the left. I'm not sure if there was a deliberate reason for this. Thank you

**Comment by pigigaldi** [comment]
Hi! Unfortunately I don’t have any type of control on that ‘x’ button and finding a way to move it could be very tedious. I’ll close this issue for now but I keep it in mind.
Thanks!

**Comment by jchonig** [comment]
This is a major usability issue.  I have muscle memory with the location of the ESC button when Pock is not running.  So if use Emacs while Pock is running I just turn off Pock.
