### ISSUE TITLE
Spotify Swipe Gestures do not work

### ISSUE THREAD

**Issue by MohamedElgharbawy** [pigigaldi/Pock#182]
**Describe the bug**
Swipe left to go to the previous song and swipe right to go to the next song do not work. Holding down on the left/right side of the widget performs the same functionality, but it does not work very well.

**How to reproduce**
```
Scroll left or right on the widget, it will not work. Hold down on the left side to go to the previous track. Hold down on the right side to go to the next track.
```

**Expected behavior**
The previous/next song should play when swiping left/right.

**Versions:**
 - macOS version: [10.14.5]
 - Pock version:  [0.5.3]

**Additional context**
I would much prefer swiping, the current functionality of holding down simply does not work very well at all.

**Comment by MohamedElgharbawy** [comment]
Update: Swiping up to go rewind and down to fast forward works pretty consistently. Also, songs with longer titles seem to work better for the swiping left/right gestures.

**Comment by jsonnet** [comment]
I noticed you have to remain on the NowPlaying widget when swiping. Especially with small moves it works better, but thus said already very small moves triggers the prev or next song, which could explain the _Hold down on the left side to go to the previous track. Hold down on the right side to go to the next track_ behaviour! There should probably be a minimum distance for swipeLeft and swipeRight.

**Comment by pigigaldi** [comment]
The latest version of Pock includes three different styles for the **Now Playing** widget. You can try switch to one of them to use *"physical"* buttons to skip back or forward through your songs.
