### ISSUE TITLE
Bug - Pock not visible on latest Catalina Beta (5)

### ISSUE THREAD

**Issue by tommyboylab** [pigigaldi/Pock#189]
**Describe the bug**
Pock is not showing up in the Touchbar after latest Catalina Beta (5) update 
_I'd prioritize waiting to fix this issue if it makes sense to tackle other ones; being a Beta OS and all..._
**How to reproduce**
```
1. Update to Catalina B5, 
2. Start Pock (which appears in the Menubar) 
3. Normal Touchbar is shown
4. Using the Ctrl shortcut makes the Esc key flash, but does not change Touchbar

```

**Expected behavior**
1. Upon Starting Pock, Pock should change to be Touchbar
2. Using the Ctrl Key should switch the Touchbar between normal and Pock

**Screenshots**
Not applicable, just shows normal Touchbar

**Crashlog**
Not applicable, app does not crash

**Versions:**
 - macOS version: 10.15 B5
 - Pock version:  0.5.3

**Additional context**
Esc key flashing on Ctrl key shortcut is the only indication that Pock is probably working, might be working, just not visible.

**Comment by tommyboylab** [comment]
Update: Seems to occur when Expanded Control Strip is set as the default Touchbar in settings. I just wiped my laptop and Pock is working as expected; until I change the default Touchbar.

**Comment by pigigaldi** [comment]
This is expected behavior if `Hide Control Strip` option is disabled in Pock settings since `Expanded Control Strip` prevent other apps from showing custom content on Touch Bar.

**Comment by RonanMacF** [comment]
Coming across the same bug. Unable to get pock working at all since upgrading to catalina
