### ISSUE TITLE
No track info in 'now playing' when casting to device (from Spotify)

### ISSUE THREAD

**Issue by nwesthoff** [pigigaldi/Pock#196]
**Describe the bug**
When casting with Spotify (chromecast) Now playing doesn't show track/artist info.

**How to reproduce**
```
1. Play song
2. Cast to chromecast (possibly other devices too)
3. See Spotify icon, but no track information
```

**Expected behavior**
I expect it to work the same as when playing on the MacBook itself

**Versions:**
 - macOS version: 10.14.6
 - Pock version:  0.5.3

**Comment by nwesthoff** [comment]
I'd like to point out that this might actually be a problem with the way Spotify handles casting to chromecast devices, which means there's nothing Pock can really do to solve that.

However, since the touch target is so small when there's no track info, gestures are hard to trigger. Solving issue https://github.com/pigigaldi/Pock/issues/182 is important imo.

**Comment by pigigaldi** [comment]
You're right, this problem is related to the way Spotify handles casting to external speakers. If you try to reproduce a song on an external device, you should see an empty "Now Playing" widget in your Notification Center.
