### ISSUE TITLE
Make the App Exposé "feature" Optional

### ISSUE THREAD

**Issue by rogerluan** [pigigaldi/Pock#206]
**Describe the feature you'd like to have in Pock**

The recent update from 0.5.3 to 0.6.0 introduced the App Exposé feature that I don't quite enjoy. It'd be great to have it as a setting to be toggled via settings.

**Describe alternatives you've considered**
Downgrading to v0.5.3.

**Additional context** 
I understand that this is being distributed as beta (or alpha) and that "breaking" changes will happen, but I guess that any major changes like this (sp. related to UX) should be introduced as an opt-in feature instead of forcing everyone to accept it 😬 

Regardless, I've been using Pock for a couple months now and I love it. It's absolutely great and changed the way I use the touch bar! ❤️

**Comment by Looki75** [comment]
Aggreed. If I have several let's say "Chrome" windows, then they all look similar to each other and the app-exposé feature is pretty useless be cause you don't know where to click to go where you need to...
I reverted to 0.5.3 which is better for me: click several times on the Chrome icon and you will cycle through all Chrome windows... stop clicking when the one you want is foreground...

By the way, none of 0.5.3 and 0.6 correctly handle "Finder" to this regards: no app-exposé, no cycle through windows...

**Comment by rogerluan** [comment]
Oh I didn't know you could cycle through them by tapping multiple times. I'm too lazy to revert now, but it's been annoying since I upgraded 😅 

By the way, can't wait till we implement 3rd party plugins  😄

**Comment by jzadra** [comment]
There's an option to "Always Open app Expose" but it doesn't seem to alter the behavior (ie disabling it still opens the expose in the bar)

**Comment by rogerluan** [comment]
@jzadra that option is maybe wrongly implemented. The behavior that it changes is: when enabled, it will *always* display the exposé, even if there's only 1 app instance, instead of displaying the exposé only when there're 2 or more. I can't imagine people would actually like or use this option 😂 

It should be worded as `Never Show App Exposé` and have its internal logic fixed 😜

**Comment by pigigaldi** [comment]
> @jzadra that option is maybe wrongly implemented. The behavior that it changes is: when enabled, it will _always_ display the exposé, even if there's only 1 app instance, instead of displaying the exposé only when there're 2 or more. I can't imagine people would actually like or use this option 😂
> 
> It should be worded as `Never Show App Exposé` and have its internal logic fixed 😜

It's not wrongly implemented, that's just the way I decided to implement it. 😅 But I agree with the fact that I should consider another case, where a user doesn't want the App Exposé at all. I'll implement it asap. 🌱 Thanks for the feedback! 🙏

**Comment by rogerluan** [comment]
@pigigaldi ☝️ hopefully I was faster and we didn't double up on work haha. This took me 20mins 😛 
Hope it's fine without the tests.

**Comment by Feanaaro** [comment]
Please forgive my ignorance as a non-programmer... but, is it possible for me to manually swap the setting file(s) so as to have this feature? I couldn't figure it out on my own.
Love the program, but the behavior of the expose as it is now makes it much less useful.

**Comment by rogerluan** [comment]
Nope @Feanaaro .

But I compiled it for you haha there you go.

[Pock.app.zip](https://github.com/pigigaldi/Pock/files/3672142/Pock.app.zip)

**Comment by Feanaaro** [comment]
Thanks!

**Comment by pigigaldi** [comment]
I'm sorry @rogerluan but I had to remove the link to your compiled version since I need to do a safe-release with analytics framework to track if there are issues in public releases.
I'm going to merge your PR asap, and I'll release 0.6.2 just after that.
Thanks for your patience folks!

**Comment by rogerluan** [comment]
Thanks @pigigaldi !

This was implemented and released in https://github.com/pigigaldi/Pock/releases/tag/0.6.1
