### ISSUE TITLE
Some more settings

### ISSUE THREAD

**Issue by ozgureffe** [pigigaldi/Pock#21]
Thank you @pigigaldi for your work. Before Pock, touch-bar was almost useless for me.
I have a request: It would be awesome if margin between icons also adjustable to prevent accidental touches...

**Comment by rperez93** [comment]
Hi and thank you @pigigaldi  for the project. 
Right now i want to disable de esc widget or edit more things too.

**Comment by iDjay** [comment]
Can you add the option to disable the check for the notification badge? At the moment you can set it between „instantly“ and „3 minutes“ but I prefer a „never“ option :) 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by pigigaldi** [comment]
Addressed in the latest release! https://pock.dev
