### ISSUE TITLE
Media Widget Play/Next/Prev Buttons

### ISSUE THREAD

**Issue by mccannt** [pigigaldi/Pock#214]
I love the Media and Volume Widgets but it would be nice to be able to have the Play/Next/Prev buttons as options much like you would have on the external keyboards.

**Comment by linuscarlstrom** [comment]
+1

**Comment by crutchcorn** [comment]
This issue is compounded by the fact that the swyping seems to work rarely for me. It's the only reason I switch away from pock anymore

**Comment by mccannt** [comment]
I have noticed the same thing @crutchcorn but thought maybe it was me doing something wrong. 
Not a major issue as I have an external keyboard with dedicated keys.

**Comment by L1cardo** [comment]
I tried to add such Play Next Prev buttons. It is not difficult, and also not necessary I think , because you can tap the icon to play and pause, swipe to change Next and Prev.
If swipe left or right doesn’t work for you, you should try swipe up or down.

**Comment by mccannt** [comment]
@L1cardo Its not about if its necessary or not here, thats your personal opinion. 

It's a request for the feature as the current implementation does not always act as intended, so this is an alternative.

If it is easy to add those buttons, please add them or if you can guide us on how to. I would be happy to give it a shot :)

**Comment by L1cardo** [comment]
Swipe up to Prev and swipe down to Next, this works fine, did you try this?
If you insist, I will consider. But there are already too many buttons , I don’t know if @pigigaldi will accept that.

**Comment by mccannt** [comment]
I have tried this. It does work at times, other times it's non-responsive. 

One thing I love about this app is how useful it makes the touch bar now and the fact that I can customize it to my personal needs. I have no expectations on this being solved, its more of a suggestion I made based on my preferences. 
I am by far no developer anymore but I am happy to give it a shot to add these with some guidance.

**Comment by L1cardo** [comment]
No worries, I will try to add those buttons. 
Whether it will be eventually on the release version of Pock depends on @pigigaldi

**Comment by mccannt** [comment]
Awesome. It's much appreciated it. :)

**Comment by pigigaldi** [comment]
I was thinking about a couple of ideas for this.
```
1. Add media player buttons in ControlCenter widget
2. Use an alternative layout for the NowPlaying widget (maybe toggle between layouts with a double-tap or a dedicated element/button?)
3. Create a new widget with only the media controls (something like a `MediaControl Widget`)
```
I still need to figure out which one could be the right choice.
What do you think?

**Comment by L1cardo** [comment]
Here is my idea:
1. Make the NowPlaying widget more sensitive, because swipe left or right sometimes works but sometimes not(make the whole NowPlaying widget swipeable ,not just the icon or the title)
2. A new separated MediaControl Widget


But I think No.1 is the best solution

**Comment by mccannt** [comment]
Just putting in my 2 cents on this. 

I like the idea of a MediaControl Widget but also see the benefits of improving the current NowPlaying widget.

Would it be possible, maybe not easy, to make the NowPlaying widget more contextual? 
Meaning if I tap the NowPlaying widget, or hold it for X seconds. That it will display the media navigation controls.

That way it kind of satisfies all requirements. Keeps it working as it is today but extends its functionality to allow users to have another way to interface and navigate their media.

**Comment by pigigaldi** [comment]
The latest version of Pock now includes three different styles for the **Now Playing** widget.

**Comment by mccannt** [comment]
Great work on this and thank you very much!
