### ISSUE TITLE
'Now playing' shows iTunes icon when Spotify is playing

### ISSUE THREAD

**Issue by steynvanesveld** [pigigaldi/Pock#217]
Even though Spotify is playing music, Pock shows the iTunes icon in the 'now playing' widget.
This wasn't the case in the 0.5.X version of Pock, only since the 0.6 update.

I've tried removing the widget, relaunching the app a couple of times, but this issue is still persistent.

This isn't really a bug, since the icon does actually still show Spotify's data, but it could be a bit better.

**Comment by hntddt123** [comment]
0.5.X version was better UX with not playing (you can touch to launch music app) and now playing (shows icon and song)
