### ISSUE TITLE
Double tap to switch between windows of the same app

### ISSUE THREAD

**Issue by alfie84** [pigigaldi/Pock#22]
Awesome work, I didn't paid attention to the touch bar until now! I was thinking about how you would use it to switch between windows of the same app so maybe double tap could work or exposé or whatever its called.

**Comment by rajington** [comment]
Could it just be a single tap (after activation)?

**Comment by rajington** [comment]
Seems like the author intends to do something different there https://github.com/pigigaldi/Pock/blob/50e977a951b9620d04fccf9b79c9f738da184d0d/Pock/Widgets/Dock/PockItemView.swift#L154

**Comment by alfie84** [comment]
Yeah, single tap on the active app sounds like a better option

**Comment by jebrii** [comment]
I second the need for this. I suggest mimicking the behavior as it works in the regular dock.

Web browser windows across multiple Spaces make for a good use case to consider. If, for example, I have two Google Chrome pages open in one Space and a third open in another Space, taps on the Google Chrome icon in Pock might do the following:
1st tap - Focus the app, and thus the first open browser window
2nd tap - Focus the next (second) browser window, bringing it to the front (but not changing Spaces)
3rd tap - Focus the next (third) browser window, moving to the appropriate Space and bringing it to the front
4th tap - Focus the first window again, moving back to the original Space

**Comment by jebrii** [comment]
I should note, this behavior wouldn't be timing-dependent. Any pause in between taps doesn't change what the next tap will do.

**Comment by mikew** [comment]
This is how I used my shortcuts in BetterTouchTool, it's really nice. I'd expect it to work just like <kbd>Command+`</kbd>, and not do anything fancy like change spaces. [It was fairly simple in AppleScript](https://gist.github.com/mikew/d75c2dbb636dd5ba81d6be960540f905), albeit a little slow. I'm guessing it would be more effort in Swift, however.

**Comment by jebrii** [comment]
The current functionality changes Spaces when switching to an App whose primary window is in a different Space. If possible, I think it'd be nice to also change spaces when switching between windows in the current app (by tapping on the icon of the currently open app - the feature suggested in this thread).

**Comment by mikew** [comment]
> The current functionality changes Spaces when switching to an App whose primary window is in a different Space.

Pretty sure that's a macOS thing, not something programmed into Pock.

**Comment by jebrii** [comment]
> > The current functionality changes Spaces when switching to an App whose primary window is in a different Space.
> 
> Pretty sure that's a macOS thing, not something programmed into Pock.

I believe you're right about that. I'm just doing my best to make a case for the functionality that would work best for _my_ particular workflow 😄.

If changing Spaces isn't in scope for this Request, I can make another one once this has been resolved and take a whack at it myself.

**Comment by pigigaldi** [comment]
App Exposé feature is finally available from version 0.6

**Comment by rajington** [comment]
@pigigaldi wow App Exposé is really cool and really shows off the power of the touch bar, great job.

I do think there may be some users that want a more consistent static representation of their dock apps they can quickly tap on to cycle through open windows. App Exposé's tiny delay and requirement to look at the touch bar is what I'm trying to avoid.

Completely get this may not be the vision you had in mind or want to support, so I understand completely if you don't wish to re-open.
