### ISSUE TITLE
widget time module can't sync with system time

### ISSUE THREAD

**Issue by isofia** [pigigaldi/Pock#221]
widget time module can't sync with system time

widget time stopped at 13:30

**Comment by willvousden** [comment]
I have the same problem.  It shows the time that I added the widget to the touch bar.  It seems to update the time whenever I change the widget's preferences.

Other things (e.g., battery level) seem unaffected.

**Comment by apairofcleats** [comment]
Same problem as above, time on touchbar doesnt keep up with system time.

**Comment by pigigaldi** [comment]
Duplicate of #215
