### ISSUE TITLE
Battery Extends above 100 %

### ISSUE THREAD

**Issue by zacharymacke** [pigigaldi/Pock#225]
**Describe the bug**
When charging the battery icon will spill over the battery symbol.

**Screenshots**
<img width="1085" alt="Touch Bar Shot 2019-09-01 at 11 29 47 AM" src="https://user-images.githubusercontent.com/37708924/64079326-d403bf00-ccab-11e9-9659-a44e9b5898bb.png">

![IMG_8565](https://user-images.githubusercontent.com/37708924/64079382-820f6900-ccac-11e9-97d6-4740dc63e724.jpg)

**Versions:**
 - macOS version: 10.14.5
 - Pock version:  0.6

**Comment by pigigaldi** [comment]
That's what happens if you keep your MacBook attached to the charger all night long! 😅 
Joking apart, I'll surely take a look into this. Thanks for pointing it out!

**Comment by zacharymacke** [comment]
@pigigaldi just wanted to update and close this out. I haven't been able to reproduce this in some time. Not sure what update took care of it but it is working as expected!
