### ISSUE TITLE
Pock not active after long (2day) sleep and "launch at login" reverted to unticked status

### ISSUE THREAD

**Issue by tegotha** [pigigaldi/Pock#226]
normally Pock remains active when starting up from a sleep session. But when sleep took so long that i was asked to provide password to relogin (Touch ID not acceptable), Pock is not running anymore and i need to restart manually. Then when checking in preferences "launch at login" tickbox is now unticked

**Comment by zhouxingchijay** [comment]
In regards "launch at login", there is a work around that you manually add pock to your user login item. It is located under System Preferences - Users & Groups - Login Items(right hand side). click + to add pock.

**Comment by pigigaldi** [comment]
https://github.com/pigigaldi/Pock/commit/9c4fbfc23581135e5fdb63248753ade319ffe742
