### ISSUE TITLE
Now Playing widget Showing title of the song when paused and not whilst playing

### ISSUE THREAD

**Issue by ahmedu007** [pigigaldi/Pock#230]
**Describe the bug**
Whilst listening to youtube music, through a [3rd party app](https://ytmusic.app/), the name of the song doesn't appear until the song gets paused. 

**How to reproduce**
```
1. Go to 'https://ytmusic.app/'
2. Install the app
3. Play any song
4. Pause the song using now playing widget
```

**Expected behavior**
A clear description of what you expected to happen.

**Screenshots**
Whilst the song is Playing:
![image](https://user-images.githubusercontent.com/30743917/64688700-d1ac1c80-d484-11e9-828d-29a668ba5f87.png)

Whilst the song is paused:
![image](https://user-images.githubusercontent.com/30743917/64688739-e5578300-d484-11e9-8a90-97d6745ee98d.png)

**Versions:**
 - macOS version: [10.14.6]
 - Pock version:  [0.6]

**Additional context**

**Comment by pigigaldi** [comment]
I can reproduce this issue but, unfortunately, there's nothing I can do to fix this right now. The same behavior happens in the "Now Playing" widget placed in the system Notification Center and both Pock and this widget uses the same private framework to get media information.
