### ISSUE TITLE
Pock "launch on login" does not stay checked. Does not refresh time in touch bar

### ISSUE THREAD

**Issue by Goldendeed** [pigigaldi/Pock#232]
**Describe the bug**
A clear description of what the bug is.

**How to reproduce**
```
1. Go to 'menu'
2. Click on 'open pock on login'
3. Log out and log back in
4. See error

Pock is also not refreshing the time, but the battery percentage reporting is working fine.

**Versions:**
 - macOS version: [e.g. 10.14.6 (*required)]
 - Pock version:  [e.g. 0.5.2   (*required)]

**Additional context**
Add any other context about the problem here.

**Comment by MasterMindSudo** [comment]
I have the same issue too, time is not updating, it only updates when I change the setting and the panel refresh, im on the 2019 MacBook Pro 15inch

**Comment by jtchristie** [comment]
I have the same issue, I am using 2018 MacBook Pro 13 Inch.

**Comment by pigigaldi** [comment]
Version 0.6.1 solves `Launch at Login` issue.
Please, separate issue requests instead of opening one that lists multiple bugs.
And be sure to check if a similar issue was previously opened for the bug you want to report. Time syncing issue was already stated in #215
