### ISSUE TITLE
Only show Pock on desktop

### ISSUE THREAD

**Issue by andrazvonar** [pigigaldi/Pock#238]
**Describe the feature you'd like to have in Pock**
I only want to see pock when I'm on the desktop, with no windows active. Otherwise I want to see app controls.

**Describe alternatives you've considered**
The alternative is not using pock, as this is normal behaviour, except for loosing the dock which pock provides.

**Comment by pigigaldi** [comment]
You can achieve this behavior by disabling “Hide Control Strip” option in Pock settings and toggling Pock visibility trough its close button on the most left of your Touch Bar.
