### ISSUE TITLE
Add hotkey shortcut to switch between full-sized Pock and Control Strip

### ISSUE THREAD

**Issue by maxonlinux** [pigigaldi/Pock#24]
I am really impressed by your awesome work, but it's missing one very useful thing: if Pock is in so called "full-sized" mode, you aren't able to use the Control Strip. So, it will be a great option to make simple hotkey that will switch between the Pock and the normal Touch Bar.
P.S. There would be another great option to make Pock hide when you are typing or making another stuff. So, Touch Bar might be quite useful in some context-related tasks and it needs to be shown sometimes.

**Comment by MSQRD-dot-com** [comment]
I second this! I'm happy to help and create an icon for it as well.

**Comment by BLamy** [comment]
I was able to hack this behavior in by modifying the AppDelegate. 

Pock runs in 'full-sized' mode at all times. If I hit fn then i get the expanded control strip.

My settings are like this
![image](https://user-images.githubusercontent.com/324928/58999890-f4ab9e00-87bc-11e9-9216-88e5f53e8ff7.png)

```swift
    /// Finish launching
    func applicationDidFinishLaunching(_ aNotification: Notification) {
        // Insert code here to initialize your application
        NSApp.isAutomaticCustomizeTouchBarMenuItemEnabled = true
        
```
