### ISSUE TITLE
YoutubeMusic track switching doesn't work

### ISSUE THREAD

**Issue by artemovech** [pigigaldi/Pock#240]
User has no possibility to switch track in YouTube music app (browser or YT Music app).

1. Turn ON track in YT Music
2. Try to switch track via swap

Expected: tracks switch to next/previous

Versions:
 - macOS version: 10.14.6
 - Pock version:  0.6.1

**Comment by pigigaldi** [comment]
This is not a Pock bug; in fact, you can't switch to next/previous song on YouTube Music neither with system keys. 
Refers to this comment for further explanation: https://github.com/pigigaldi/Pock/issues/230#issuecomment-536736164
