### ISSUE TITLE
Control Center Missing

### ISSUE THREAD

**Issue by L1cardo** [pigigaldi/Pock#243]
**Describe the bug**
Control Center Missing. Other widgets are working well, but only the Control Center is missing.
Same as #142 

**Screenshots**
![截屏2019-10-02下午2 14 43](https://user-images.githubusercontent.com/33802186/66022009-23dddc00-e51f-11e9-91ef-fa1f976f102b.png)
**Versions:**
 - macOS version: [10.15 Beta版(19A578c)]
 - Pock version:  [0.6.1]

**Comment by rNiedzwiecki** [comment]
Same happens on macOS 10.14.6. I will take a look on this tomorrow.

**Comment by L1cardo** [comment]
my macnook is `MacBook Pro (13-inch, 2018, Four Thunderbolt 3 Ports)` and control center is missing.
but my friend's macbook is `MacBook Pro (15-inch, 2019)` and control center works fine

**Comment by L1cardo** [comment]
I have found the reason.
The control center widget is missing only when you are running `touch-bar-simulator` and with your MacBook closed (connected to a display and keep the MacBook closed).
So if you open the case of your MacBook , and quit the `touch-bar-simulator`, the control center widget appears again.

So this is a `touch-bar-simulator` bug, not a Pock bug.

**Comment by ericstumper** [comment]
I have never used touch-bar-simulator and the control center is missing on 10.14.6 Macbook Pro 2017 4 Thunderbolts.
