### ISSUE TITLE
crashes when you click on chrome icon to show different windows

### ISSUE THREAD

**Issue by gpar1234** [pigigaldi/Pock#247]
**Describe the bug**
When you have pock open and you tap on the chrome icon it doesn't open the different windows. Instead, it crashes

**How to reproduce**
1. Open pock
2. Tap chrome icon
3 Pock doesn't open different windows: it crashes instead

**Expected behavior**
I expected it to open the different windows of chrome

**Screenshots**
![image](https://user-images.githubusercontent.com/56208993/66262222-09129e00-e791-11e9-8ac6-bef288347226.png)

**Crashlog**
If applicable, add crashlog to help me investigate your problem.
Attached below:
[file type not supported]

**Versions:**
 - macOS version: 10.14.5
 - Pock version: 0.6

**Additional context**
N/A

**Comment by pigigaldi** [comment]
Please, update to 0.6.2 and let me know if this issue still occurs.
