### ISSUE TITLE
Brightness up/down and volume up/down buttons not working in 10.15 Catalina

### ISSUE THREAD

**Issue by apairofcleats** [pigigaldi/Pock#248]
**Bug Description:**
The volume up/down and brightness up/down buttons do not change the volume or brightness after upgrading to OSX 10.15 Catalina.
They still bring up the volume/brightness slider if you long press the up/down button, but for single touch pushing, it does not change the volume or brightness

**Steps to reproduce the behavior:**
Upgrade to 10.15 Catalina... no other changes made.  Tried reinstalling Pock but didn't seem to make a difference.

**Expected behavior**
The buttons would increase or decrease volume/brightness by one step

**Versions:**
 - macOS version: 10.15 Beta (19A582a)
 - Pock version:  0.6

**Comment by Swordstar2002** [comment]
Same here with Catalina 10.15 although before logging in, they both work properly.

**Comment by pigigaldi** [comment]
Please, try resetting Accessibility authorization and let me know if it fixed your issue 👍

**Comment by Swordstar2002** [comment]
After 2 hours on to Apple Support having restarted in Safe mode, reinstalling Catalina and several other suggestions, I had to create a new user and copy everything except my user Library to the new user account. This solved the issue but took several hours. Email accounts do not just transfer etc.. Sledgehammer to crack a nut. Not impressed.

Thanks for the suggestion though!
