### ISSUE TITLE
Clock not refreshing

### ISSUE THREAD

**Issue by andre-lergier** [pigigaldi/Pock#251]
The time (in 24h format) in the date item from the status widget is not refreshing. It just stays on the time from starting pock.

I removed it, added it again and restarted pock, but it didn't change.

**Versions:**
 - macOS version: [10.14.6]
 - Pock version:  [0.6.1 ]

**Comment by pigigaldi** [comment]
Please, check releases before opening new issues 😄
Update to [0.6.2](https://github.com/pigigaldi/Pock/releases/tag/0.6.2)

**Comment by andre-lergier** [comment]
I'm sorry, it didn't show this release in _Preferences -> Check for updates_. 😉
