### ISSUE TITLE
Add 'Start Screensaver' as option in Control Center Widget

### ISSUE THREAD

**Issue by jayjanssen** [pigigaldi/Pock#256]
**Describe the feature you'd like to have in Pock**
Similar to 'Sleep' and 'Lock' screen -- I want a button that will instantly start my screensaver.  This is the equivalent of Lock, except that it would leave my display on.  

**Describe alternatives you've considered**

I use the lock item now, but it blacks my display almost immediately.

**Comment by L1cardo** [comment]
I will see if I can working on it , but not a promise.

**Comment by L1cardo** [comment]
@pigigaldi I have found a way to start screensaver by using Appel Script. Do you have a better solution?

**Comment by L1cardo** [comment]
> **Describe the feature you'd like to have in Pock**
> Similar to 'Sleep' and 'Lock' screen -- I want a button that will instantly start my screensaver. This is the equivalent of Lock, except that it would leave my display on.
> 
> **Describe alternatives you've considered**
> 
> I use the lock item now, but it blacks my display almost immediately.

 I don't know if this is good for you https://github.com/pigigaldi/Pock/pull/274#issuecomment-549875025
[Demo Here](https://youtu.be/rxO8aHXDg6M)

**Comment by koryva** [comment]
![image](https://user-images.githubusercontent.com/1869511/68798856-2c98f600-0625-11ea-9c51-5fd04bd38a89.png)

I was sorta able to make it work by tweaking both the "hide control strip" and displaying Pock settings.

For example:

1. Hide Control Strip is unchecked.
2. Control center widget "show lock item" is unchecked.
3. For the default TouchBar settings, I dragged the "screensaver" icon to it.
4. As you can see in the screenshot, I now have both Pock and the screensaver icon on the TouchBar at the same time. The only other default (non-Pock) icon I'm using is the Spotify icon; everything else is Pock including the volume controls.

Hope this helps.

**Comment by L1cardo** [comment]
@koryva Cool! But you should really watch my video [here](https://youtu.be/rxO8aHXDg6M)

**Comment by jayjanssen** [comment]
This feature was added in the latest version of Pock. Closing this issue.
