### ISSUE TITLE
Where do I change app language from?

### ISSUE THREAD

**Issue by lcukerd** [pigigaldi/Pock#260]
I don't see the option anywhere. The language got changed to some weird language.

**Comment by L1cardo** [comment]
It changes automatically based on your system language

**Comment by lcukerd** [comment]
The system language is set to English only. It happened since the last time I built the project. I am on the latest master commit "Use NotificationCenter to reload ControlCenterWidget" and the only diff is in xcsheme (certificates). Any idea what happened?

**Comment by L1cardo** [comment]
What is your system language?
What is pock’s language?
And what language do you want pock to be set ?

**Comment by lcukerd** [comment]
System Language: English
Pock Language: Italian
Want it to be English

**Comment by L1cardo** [comment]
Ok I get it. The release version is fine and got no this issue.
Somehow the build language was modified by someone.
You can set build language to default by [this ](https://github.com/pigigaldi/Pock/pull/255/files)

**Comment by lcukerd** [comment]
Removing `language = "it"` doesn't seem to change anything. Neither does replace it with `language = "en"`. Did you mean something else?

**Comment by L1cardo** [comment]
Just remove the ‘language = it‘ line and clean build folder and build , done!
This is what I did, and it worked.

**Comment by pigigaldi** [comment]
You can simply edit Pock `Scheme` and change its `Options` to switch `Application Language` back to `System Language`.

<img width="859" alt="Schermata 2019-10-16 alle 09 29 56" src="https://user-images.githubusercontent.com/422119/66897551-8642dc00-eff7-11e9-81ad-1d6ecb945e82.png">
