### ISSUE TITLE
Lock "Now Playing" Widget to Spotify

### ISSUE THREAD

**Issue by Nornode** [pigigaldi/Pock#267]
**Describe the feature you'd like to improve in Pock**

1. Start playing music on Spotify, and enjoy. 
2. Now you need to watch a short instructional  (any) video on Youtube. 
3. You need to pause Spotify to hear the Youtube video sounds. 
4. Click "Now playing" widget and you pause the Youtube video instead of Spotify as it changed the controlling media entity. 
5. This (for me) ends up with a sequence of:
A pausing video - B finding Spotify C Pause spotify D find chrome window and tab E start playing video... :|  -- And then the reverse when going back to Spotify as I probably will leave the tab open...

Instead, when Playing various youtube videos I want to pause my Spotify when the video starts (or other media). Now Playing widget exchange the entity it's controlling and I end up pausing the video instead of my Spotify music that continues to play.

I wish to Lock the "Now playing" widget to always control Spotify independently from any other media playing entity, be it, VLC Chrome or something else. 

**Describe alternatives you've considered**
I haven't considered any other alternative.

**Comment by grrowl** [comment]
I'm assuming Pock uses MacOS's system "play/pause" functionality to control media. The problem here is that Chrome handles system "play/pause" commands to control youtube and other websites, which is dumb as hell (imo) — you can change Chrome's behaviour by navigating to `chome://flags` and settings "Hardware Media Key Handling" to "Disabled" and restarting Chrome.

**Comment by pigigaldi** [comment]
@grrowl What you said is right! Anyway, that line of code let Pock show the **Safari** icon when `MediaRemote.framework` gets information about media playing from **Safari**.

**Comment by Nornode** [comment]
I'm still having this issue and I think it's a valid use-case.
Why not be able to lock or prioritize  "Now Playing" to one media player?
