### ISSUE TITLE
No menu

### ISSUE THREAD

**Issue by molbrown** [pigigaldi/Pock#276]
**Describe the bug**
I downloaded Pock and it showed up in my touch bar with what looks like default settings (exactly mimics my dock, no widgets). Looking to customize and add any of the widgets, I tried opening the app to access the Preferences or Customize menu items, but can't get the app menu anywhere.

**How to reproduce**
Download, unzip, and open Pock.

**Expected behavior**
I expected to access Preferences and Customize via an app menu.

**Crashlog**
n/a

**Versions:**
 - macOS version: 10.14.6
 - Pock version:  0.6.3 (latest)

**Additional context**
I removed the app from my computer in favor of the Apple touchbar, until I can customize Pock to work for me.

**Comment by KorovinViktor** [comment]
The same

**Comment by godested** [comment]
The same

**Comment by jmberrueta** [comment]
The same

**Comment by mklebrasseur** [comment]
I was able to get access to all widgets and preferences by using the top menu bar and clicking the pock icon.

**Comment by jmberrueta** [comment]
> I was able to get access to all widgets and preferences by using the top menu bar and clicking the pock icon.

This!

**Comment by molbrown** [comment]
☝️ Is also now working for me, closing issue.
