### ISSUE TITLE
My Touchbar does not display the core features for volume and brightness anymore

### ISSUE THREAD

**Issue by trailblazr** [pigigaldi/Pock#28]
My Touchbar does not display the volume and brightness buttons anymore, though on the MBP of my college this is still present if you "scroll" the dock icons to the absolute left.

See this screenshot...

<img width="1085" alt="Touch Bar Bild 2019-04-01 um 12 56 31" src="https://user-images.githubusercontent.com/339705/55322882-c2f51e80-547d-11e9-9bd4-f3a3dff67be9.png">

**Comment by pigigaldi** [comment]
Can you please check if you have "Hide Control Strip" option enabled by mistake?

**Comment by trailblazr** [comment]
Actually I need to check the "Hide Control Strip" option to actually activate the Dock icons on the Touchbar. Maybe this has something to do with it. I'd love to use this awesome tool. But I heavily rely on brigthness and volume-controls. See following screenshots on which combination results in which kind of touchbar. 
![pock_bar](https://user-images.githubusercontent.com/339705/55400426-25b5eb00-554e-11e9-8df6-9555c9af5c8c.png)

**Comment by adamhairfield** [comment]
I have this same issue.

**Comment by pigigaldi** [comment]
Please make sure you have `Show App Controls with Control Strip` option in your Keyboard settings.

**Comment by trailblazr** [comment]
This was it! Fixed the issue... have a look at these settings:
![pock_works](https://user-images.githubusercontent.com/339705/55474694-17c99e00-5612-11e9-90c3-df3bc720e308.png)

**Comment by pigigaldi** [comment]
Great! 🎉
