### ISSUE TITLE
Instructions to Uninstall

### ISSUE THREAD

**Issue by JakeHartnell** [pigigaldi/Pock#282]
**Describe the feature you'd like to improve in Pock**
There should be instructions to remove Pock.

**Describe alternatives you've considered**
I've done a Google search, and also searched the issues.

**Comment by pigigaldi** [comment]
Hi! You can move `Pock.app` to trash to uninstall it 🏌🏻‍♂️

**Comment by JakeHartnell** [comment]
I did, but now there is a blank space in my touch bar where Pock use to be... : /
![touchbar](https://user-images.githubusercontent.com/521978/69573947-ef652a00-0f7b-11ea-9a5a-a4eece0e3eee.jpg)

**Comment by jaredtkatz** [comment]
Highly recommend AppCleaner for uninstalling any and all macOS applications:
https://freemacsoft.net/appcleaner/
