### ISSUE TITLE
Launch at login option won't remain checked

### ISSUE THREAD

**Issue by ruairiphackett** [pigigaldi/Pock#286]
**Describe the bug**
The `Launch at login` setting doesn't work. When it is is checked and the `Preferences` reopened, it will be unchecked.

**How to reproduce**
```
1. Go to `Preferences`
2. Check the `Launch at login` checkbox
3. Close `Preferences`
4. Reopen, the checkbox will be unchecked
5. When restarting computer `Pock` does not launch & needs to be started manually
```

**Note:**
I enabled all the permissions [here](https://pock.dev/docs/catalina.html), but it made no difference.

**Expected behavior**
Pock to launch at login when setting is applied

**Screenshots**
Video of issue: https://screenshot.click/26-33-38tlc-j1gpu.mp4

**Crashlog**
If applicable, add crashlog to help me investigate your problem.
``` 
1. Open the Console application located at "Application -> Utilities -> Console.app."
2. Click on "User Reports" in the left menu, then locate the latest Pock crash report. (You can filter reports by typging "pock" into the searchbar on the top)
3. "ctrl + click" on the latest Pock crash report and click on "Reveal in Finder" option, then attach the .crash file in this issue.
```

**Versions:**
 - macOS version: `10.15.1`
 - Pock version: `0.6.3`

**Additional context**

**Comment by L1cardo** [comment]
This has been fixed, just wait for next release!

**Comment by ruairiphackett** [comment]
Landed this morning thanks!
