### ISSUE TITLE
Certificate of Official website has expired

### ISSUE THREAD

**Issue by iDevOrz** [pigigaldi/Pock#288]
➜  ~ brew cask install pock
==> Downloading https://pock.dev/download.php?file=pock_0_6_3.zip
-=#=#   #   #
curl: (60) SSL certificate problem: certificate has expired
More details here: https://curl.haxx.se/docs/sslcerts.html

**Comment by pigigaldi** [comment]
Renewed now! Sorry for the inconvenience!
