### ISSUE TITLE
Add the possibility to hide the menu bar icon

### ISSUE THREAD

**Issue by beppedessi** [pigigaldi/Pock#296]
I, and probably like me a lot of people who appreciates your this useful app, let Pock.app opened at all times, and once It has been customised i can't see the utility to let showed the menu bar icon. I don't know for other people but my menu bar is really crowded and hiding icons that I don't use at all is great. But I can do It for Pock. Do you think It could be useful?

**Comment by L1cardo** [comment]
You can try Dozer

**Comment by pigigaldi** [comment]
I think it is better to leave that icon there since it can always be useful to close/customize Pock easily.
You can try [Dozer](https://github.com/Mortennn/Dozer), as @L1cardo suggested.

**Comment by danielbayley** [comment]
@pigigaldi This should be a minimum standard option in _all_ macOS apps that add menu bar items! Don't impose things on users… especially forcing them to install _another_ app in place of a simple preference. Pock can be easily launched with Spotlight or Alfred to access preferences… there is no _need_ for another menu bar item, if the user doesn't want it.

Appreciate this app though, and I'll likely be contributing PRs in future…

**Comment by L1cardo** [comment]
> @pigigaldi This should be a minimum standard option in _all_ macOS apps that add menu bar items! Don't impose things on users… especially forcing them to install _another_ app in place of a simple preference. Pock can be easily launched with Spotlight or Alfred to access preferences… there is no _need_ for another menu bar item, if the user doesn't want it. This issue should be reopened.
> 
> 
> 
> Appreciate this app though, and I'll likely be contributing PRs in future…

Actually this is just about one line of code, but we may need to wait until @pigigaldi finish the widget migrations
