### ISSUE TITLE
Brew installation?

### ISSUE THREAD

**Issue by mrjackdavis** [pigigaldi/Pock#31]
Hi!

Would you be open to getting this on `brew`? Or as a `brew cask`?

**Comment by ffloimair** [comment]
I'm planning to work on a cask this evening

**Comment by pigigaldi** [comment]
Please, don't distribute Pock through other services (like brew or similar).
I'll publish a cask as soon as I can.
Thanks!

**Comment by xlc** [comment]
I love brew cask installation as well. I think it is more importantly for alpha software because it simplifies the upgrade process.

**Comment by pigigaldi** [comment]
Don’t worry! The new update, that is coming soon, will include auto-update thanks to https://github.com/sparkle-project/Sparkle! 🙌🏻
