### ISSUE TITLE
Option to hide Escape "key"

### ISSUE THREAD

**Issue by Alinaki** [pigigaldi/Pock#312]
Very happy to use Pock but since I use Karabiner Elements to remap my Esc key to § key there would be  a very good option to have an ability to completely hide Escape key in the "Hide control strip" mode.

**Comment by ohemsted** [comment]
You can remove the Escape key widget from the customise menu. You can drag the widget out of the touchbar.

**Comment by Alinaki** [comment]
It is not possible at all. I can not remove Esc, it's always under Done. No way to do this.

**Comment by LucasVanDongen** [comment]
I really can't get rid of the ESC key. It's totally unnecessary on a 16" MBP.
