### ISSUE TITLE
Crash when re-opening Music.app

### ISSUE THREAD

**Issue by trevormeier** [pigigaldi/Pock#314]
When I close, reopen and start to play music in Music.app with the hide "Now Playing" widget option enabled, Pock is closed and the Music.app Touch Bar controls take over.

**How to reproduce**
```
1. Open Pock, set "Now Playing" to hide when unused
2. Open Music.app, play some music
3. Quit Music.app while music is playing (Now Playing widget will disappear)
4. Reopen Music.app 
5. Press play on an album 
--> Pock will quit
```
[Pock_2019-12-16-095428_tbook.crash.zip](https://github.com/pigigaldi/Pock/files/3968069/Pock_2019-12-16-095428_tbook.crash.zip)

**Versions:**
 - macOS version: 10.15.1
 - Pock version:  0.7.1

**Comment by L1cardo** [comment]
No need to reopen, pock crashed the first time with all music players (not jus Apple Music).
This is related to `hide when no item playing`

**Comment by pigigaldi** [comment]
A fix for this issue will be released in a few hours
