### ISSUE TITLE
Now Playing Icon does not stop bouncing 

### ISSUE THREAD

**Issue by L1cardo** [pigigaldi/Pock#315]
**How to reproduce**
```
1. open Music app
2. Play a song
3. quit Music App
4. See error
```

**Expected behavior**
Now Playing Icon stops bouncing 

**Screenshots**
![1](https://user-images.githubusercontent.com/33802186/70917037-99a21000-2057-11ea-9ee3-60b75104bcf2.gif)

**Versions:**
 - macOS version: [10.15.2]
 - Pock version:  [0.7.1]

**Comment by pigigaldi** [comment]
I can't replicate this issue. Can you please try if this also occurs with other music apps (like Spotify)?

**Comment by L1cardo** [comment]
Only with Music.
I tried Netease Music, this didn’t happen.
My setting: 
- uncheck “ hide when not playing”
- widget style only info

**Comment by pigigaldi** [comment]
I found the issue! A fix is coming. 🎉
