### ISSUE TITLE
Pock freezes and uses 50% of CPU

### ISSUE THREAD

**Issue by goldmont** [pigigaldi/Pock#32]
Hi,

I'm not able to use Pock because it freezes on launch and starts using over 50% of CPU. I'm forced to kill its process in order to turn off my fans. I have a MacBook Pro running Mojave 10.14.4. Is there anyone esperiencing the same issue?

Regards,
G.

**Comment by leozhang2018** [comment]
I got high CPU usage too.

**Comment by pigigaldi** [comment]
Do you guys still have this problem also in the last version?

**Comment by dennisreimann** [comment]
Yep, way better. From time to time it is still in the range between 5-10% CPU usage, but at least for me it doesn't freeze anymore.

**Comment by pigigaldi** [comment]
Good! I'll close this for now. Feel free to reopen if this should occur again.
