### ISSUE TITLE
Everyone have a look pls！！ ---  Default Music Player

### ISSUE THREAD

**Issue by L1cardo** [pigigaldi/Pock#324]
As Pock now has three different now playing widget styles, and if I choose `don't  hide when no playing`, it will always display the icon of Apple Music.
Would it be better if it displays your favorite music player?
May fix #104

**Tap the Touch Bar icon to open your favorite music player！！**

If you have such a demand, I will pull a request !

![image](https://user-images.githubusercontent.com/33802186/71319001-43a7ef00-24d3-11ea-96e4-f3836d564782.png)
![image](https://user-images.githubusercontent.com/33802186/71319082-23c4fb00-24d4-11ea-8eb5-c11c84cff622.png)
![image](https://user-images.githubusercontent.com/33802186/71319004-51f60b00-24d3-11ea-9a7f-8374d0e19fd0.png)
![image](https://user-images.githubusercontent.com/33802186/71319045-c3ce5480-24d3-11ea-9614-3bd355356492.png)

**Comment by ooohawk** [comment]
i cant choose the default music player
<img width="566" alt="Screen Shot 2019-12-26 at 8 23 57 PM" src="https://user-images.githubusercontent.com/43295730/71475948-a673f000-281d-11ea-9c22-1807536d003e.png">

**Comment by L1cardo** [comment]
@ooohawk This is what I have developed, it is not official yet.
So I am asking the opinion of the community,  if people want this feature, I will work to make it official.

**Comment by orthodoX** [comment]
@L1cardo Yes please!
