### ISSUE TITLE
The wrong `⎋esc` button

### ISSUE THREAD

**Issue by Toxblh** [pigigaldi/Pock#33]
The ⎋esc button doesn't exactly same as that in the native Control Strip, it seems to that the buttons are 'locked' when pressing some keys:

I cannot exit from Switch bars (⌘ ⇥tab) without triggering anything (when holding ⌘ ) by pressing esc.
Force Quit... ( ⌘⌥ ⎋esc ) cannot be triggered.
Furthermore:

(very low possibility and can be denied) Finder Browsers in some specific apps cannot be closed by pressing ⎋esc.

**Comment by 2Pock** [comment]
I am also not able to use my esc button to execute force quit.  Holding command option esc does nothing

**Comment by jinius17** [comment]
I think I have the same issue. Can't seem to make the ESC button to work.
