### ISSUE TITLE
Hit State for Icons

### ISSUE THREAD

**Issue by MSQRD-dot-com** [pigigaldi/Pock#37]
Can you add a hit state for icons to give immediate feedback to the user letting them know it's processing? Make sure whatever it stays for a second to two so that the user can see it's processing when they move their finger away. Maybe a background color (used picked via preferences) and have it flash 3 times (from 70% color to 100% pulsing back and forth) then fade to black, or outline the icon and fade, or even really fancy, explode the icon.

**Comment by pigigaldi** [comment]
Introduced bounce animation in the latest release! https://pock.dev
