### ISSUE TITLE
Not Launching at startup

### ISSUE THREAD

**Issue by 2Pock** [pigigaldi/Pock#39]
Pock is set to launch at login but is not

**Comment by pigigaldi** [comment]
Which version of Pock are you using?

**Comment by peckpeck20** [comment]
same here. I'm on 0.4.5

**Comment by 2Pock** [comment]
I’m on 0.4.5.

I think this is an awesome app I’d even be willing to pay for, but it is causing my computer to run hot at times.  If this gets addressed in future releases I will definitely check it out, but right now it is taking up to many resources on my machine.

Thanks,

Josh Rubin
rubin.josh@gmail.com
(805)660-2203

**Comment by pock66** [comment]
same here. Im on 0.4.5 and need to re start manually when my Mac boots from cold.

best thing I've seen for MacBook in a loooong time

**Comment by vincentneo** [comment]
Same issue here, on mac os 10.14.4

**Comment by middlewavemw** [comment]
Same here, macOS 10.14.4

**Comment by pock66** [comment]
Running latest pock and still won’t run on boot up

**Comment by rescaraster** [comment]
I'm on MPB Late 2016/ MacOS 10.14.15/Pock 0.4.6 
and it doesn't at login. 
There have any way to solve it? 

thanks for your support

**Comment by tejasgarde** [comment]
Awesome app really good work .
I am facing same issue MBP 2018/MacIS 10.14.5/Pock 0.4.6
Also please update README.md file on how to contribute for bug fix and enhancements

**Comment by misselvexu** [comment]
MacBook Pro (15-inch, 2018)
Mojave 10.14.5 .
Pock 0.4.6 , not startup at login yet .

**Comment by slmccart** [comment]
Any update on when this might get some attention? As others have said, I use the app all the time, and it works flawlessly. The only issue I've seen is not launching at startup, despite setting that in the preferences.

MacBook Pro (15-inch, 2018)
Mojave 10.14.5
Pock 0.4.6

**Comment by MateuszDabrowski** [comment]
Same for Macbook Pro (2018, 15') / Mojave 10.14.5 / Pock 0.5.2

**Comment by akacaz** [comment]
Same here at 10.14.5 MBP 13inch 2016

**Comment by mediter** [comment]
same here macOS 10.15 Beta (19A512f) with Pock v0.5.3

Also, the "Launch at Login" option doesn't persist. After check this option, close and reopen the preferences, it's not checked. I have tried delete everything related to Pock except the app itself, that doesn't fix the problem.

**Comment by alexlee-dev** [comment]
Having the same issue.

macOS Mojave v10.14.16

MacBook Pro 13-inch, 2018

**Comment by duel007** [comment]
I am also experiencing this issue on Mojave 10.14.6.
