### ISSUE TITLE
Pock Button from control fails to launch pock strip

### ISSUE THREAD

**Issue by AarshApple** [pigigaldi/Pock#396]
**Describe the bug**
When we close the pock strip from the x button on left and try to reopen it from the pock button it does not open.

**Expected behavior**
Expected to toggle pock strip.

**Comment by dantebarba** [comment]
Seen this as well.

**Comment by ZhouC-J** [comment]
I also found this problem, which puzzled me

**Comment by AarshApple** [comment]
It seems somehow restarting the app resolves the issue
