### ISSUE TITLE
App package for branch_inject branch?

### ISSUE THREAD

**Issue by jtopgi** [pigigaldi/Pock#4]
For some reason my running the branch_inject branch on Xcode doesn't work for me. Is it possible to release an app package of that branch?

**Comment by pigigaldi** [comment]
Nope, since `badge_inject` is just an experimental branch, it was not created with the idea to be included in a public release.

**Comment by jtopgi** [comment]
Could you package it for me since I'd like to use it however I'm unable to run it in Xcode.

**Comment by pigigaldi** [comment]
Badge support is included in [feature/preferences](https://github.com/pigigaldi/Pock/tree/feature/preferences) branch.
You can download the pre-compiled package directly from http://pock.pigigaldi.com.
