### ISSUE TITLE
Only show open apps

### ISSUE THREAD

**Issue by aegjoyce** [pigigaldi/Pock#40]
What a great little app!

Could I suggest a possible setting? I have quite a lot of apps in my Dock so scrolling through all of them and switching between them in the Touch Bar is a little cumbersome. Would it be possible to implement a setting where Pock only shows open or active apps? Would be really nice for rapid app switching. Thanks!

**Comment by lorenzofanchi** [comment]
Thinking along this concept: would be great if there were an option to hide "Recents/Favorites" Dock items in Pock.

**Comment by pigigaldi** [comment]
Introduced in the latest release! https://pock.dev
