### ISSUE TITLE
Don't see system widget nor control center

### ISSUE THREAD

**Issue by AlaaMansourTW** [pigigaldi/Pock#402]
Hi,

I downloaded pock and it seems to be very promising. I'm not sure how to add the widget or if they should be there by default but I can't see anything except the dock items and the `esc` button. I also can't seem to find the preferences for Pock. (Not sure where Preferences or Customize are?)

Cheers!

**Comment by AlaaSaadAbdo** [comment]
I figured it out, I had some problems due to my window manager.

**Comment by AlaaMansourTW** [comment]
I have figured it out. Had problems with my window manager. Sorry for opening this issue to quick
