### ISSUE TITLE
Pock doesn't hide

### ISSUE THREAD

**Issue by Slava96** [pigigaldi/Pock#407]
Pock doesn't hide while double-press `^Control`.

If i understood correct - on any screen, or application, if i double-press this shortcut - it hides Pock. But on my system - it's not truth.

MacOS version:
10.14.6

**Comment by Slava96** [comment]
At morning - Pock working correctly. Why - i dont understand

**Comment by Egwor** [comment]
I had exactly the same problem. I restarted the software after setting the 'double click' control option and that seemed to fix it.
