### ISSUE TITLE
pock.dev is down since some days

### ISSUE THREAD

**Issue by puzich** [pigigaldi/Pock#412]
**Describe the bug**
Pock.dev is down since some days. Can't download.

**How to reproduce**

```
1. Go to 'http://pock.dev'
2. See error
```

**Expected behavior**
Website opens

**Comment by sleepybuildings** [comment]
The site seems to work fine atm.

**Comment by puzich** [comment]
Oh oh. Shame on me. I installed pew.cx many many years ago and all .dev Domains are routed to localhost 😞
Thank you for you support.
