### ISSUE TITLE
Changes made to the dock does not reflect on the touchbar

### ISSUE THREAD

**Issue by sidoshi** [pigigaldi/Pock#42]
After I have removed apps from the dock, those apps are still visible in touchbar dock. I have to restart the app to reflect the updates in touchbar.

(I realise this is not a huge issue. Just wanted to make sure the issue is known.)

**Comment by pigigaldi** [comment]
I intentionally removed this feature in 0.4.5 since I needed to figure out some performance responses.
Will be reintroduced in the next release.
