### ISSUE TITLE
Option to turn off ESC Button

### ISSUE THREAD

**Issue by Dschee** [pigigaldi/Pock#43]
It would be great if I could configure to not show the "esc" button as I very rarely use it and when I have to, I can simply click the "x" button to close Pock and there I have it. Turning off the control strip **and** the escape button would let my Touch Bar really look like the new Dock. 👍

**Comment by nethunter** [comment]
+1, I think I'll try to implement it over a weekend at some point

**Comment by pigigaldi** [comment]
Next Pock update will have a separated widget for `esc` button.
You can check a preview here: https://pock.pigigaldi.com/lack/

**Comment by nethunter** [comment]
Can we see the source code somewhere?

**Comment by carsonxyz** [comment]
It would be awesome to help test out the alpha builds of that next version. I'm glad to contribute if you want. Great work!

**Comment by jbach** [comment]
@pigigaldi Any ETA on Lack yet? Eagerly waiting 👍

**Comment by axfelix** [comment]
Still looking forward to this feature! Would it be asking too much to add a toggle to remove it from the current Pock preferences, if Lack is still a long way out?

**Comment by erikfenriz** [comment]
My MacBook pro 16 inches has a physical ESC key. So, the virtual one is redundant. Please, give us an option to turn it off

**Comment by axfelix** [comment]
This feature has been available for a while, but I've noticed there's an edge case where the Esc key will still be displayed while you're in the pock settings menu and it's focused. It should be implemented already otherwise.
