### ISSUE TITLE
request: control the white space between icons

### ISSUE THREAD

**Issue by debivort** [pigigaldi/Pock#45]
I have slightly too many apps in my dock for them all to appear in the touchbar when the control strip is also shown. If I could reduce the white(black)space between the icons, they'd all fit. Would be great to have this as an option.

**Comment by robertpeteuil** [comment]
This was the very first thing I wanted to change when I saw the screenshot on the Pock website. 

I'm surprised there isn't a setting for this, as it's very important for the core use-case of running the Dock in the TouchBar.

**Comment by pigigaldi** [comment]
Introduced in the latest release! https://pock.dev
