### ISSUE TITLE
Appstore

### ISSUE THREAD

**Issue by ngehlert** [pigigaldi/Pock#49]
is there any reason you do not distribute it via the MacOS Appstore? Would be nicer for downloading/updating/etc

**Comment by mr-perseus** [comment]
It is on Homebrew Cask.

**Comment by ngehlert** [comment]
thats not really an answer to the question ;)

**Comment by pigigaldi** [comment]
Sorry for the late response!
I can't publish Pock on MAS since it uses some private API, and Apple may not accept it in its store.
