### ISSUE TITLE
Pock not auto-navigating to Finder from other desktops

### ISSUE THREAD

**Issue by bmhorne35** [pigigaldi/Pock#52]
First off,  I love Pock and I want to thank you for developing this tool, it is awesome.

But when I have multiple desktops open, I can tap on the TB to bring me to other apps no problem, except for Finder.  If there is already a finder window open on another desktop and I tap the finder icon, it won't navigate to it, where it will for other apps like safari, word, preview, etc.  Am I missing something here?

Again thank you for your time developing the app, and for free as well!  really awesome app.

**Comment by pigigaldi** [comment]
Hi! With the latest release, you can navigate Finder directly inside Pock and then open the desired directory on Finder with the "Open" button that will appear on the right side of the Touch Bar.
Re-open this if you're still facing this issue.
Thanks!
