### ISSUE TITLE
Hide 'dismiss' button

### ISSUE THREAD

**Issue by lorenzofanchi** [pigigaldi/Pock#53]
Hi, it would be great to be able to hide the 'dismiss' button on the far left of Pock (the button with the 'cross' in it). I'm constantly hitting it, instead of the Esc button, as it's in the position where the Esc button is normally.

Thanks in advance!

**Comment by pigigaldi** [comment]
If ControlStrip is visible that `dismiss` button can't be removed.
You can hide ControlStrip in Pock preferences to have the `esc` button on the far left of TouchBar.
