### ISSUE TITLE
Can't open Pock

### ISSUE THREAD

**Issue by nickybol** [pigigaldi/Pock#56]
Did something happen. Can't open the file. something to do with the certification?

Love the app btw.

**Comment by Taraan03** [comment]
Yeah the signing certificate has been revoked, and macOS won't let the app open.

![image](https://user-images.githubusercontent.com/17274484/56977365-a27eb980-6b3a-11e9-82af-58dd8729a814.png)

![image](https://user-images.githubusercontent.com/17274484/56977512-f093bd00-6b3a-11e9-93cb-3939689661b7.png)

**Comment by nickybol** [comment]
Apple isn't happy with your great app lol. Waiting for the approval then
