### ISSUE TITLE
Ability to Toggle Control Strip Using Keybind similar to fn key for Function Keys

### ISSUE THREAD

**Issue by mikozee** [pigigaldi/Pock#57]
Ability to key bind (hopefully one key) to show partial and full control strip layout similar to how the fn key works for function keys. May also include toggles, key bind or shortcut for persistent items etc. (other hidden items). Sometimes you just need to access these items quickly without going through the pock menu but want to display your beautiful well organised dock unobstructed by default.

**Comment by mikozee** [comment]
Just want to expound that if you set the fn key to show the full control strip while it is "hidden" in Pock, you can't expand the control strip because Pock takes priority. Plus I also want to keep the fn key to show the function keys and bind another key to show and the hide the control strip and or the persistent items.

**Comment by BLamy** [comment]
I was able to hack this behavior using the following code segment in the app delegate

```swift
    /// Finish launching
    func applicationDidFinishLaunching(_ aNotification: Notification) {
        // Insert code here to initialize your application
        NSApp.isAutomaticCustomizeTouchBarMenuItemEnabled = true
        
        var isHoldingFunction = false;
        NSEvent.addGlobalMonitorForEvents(matching: .flagsChanged) {
            switch $0.modifierFlags.intersection(.deviceIndependentFlagsMask) {
            case [.function]:
                if (defaults[.hideControlStrip]) {
                    isHoldingFunction = true;
                    defaults[.hideControlStrip] = false
                    NSWorkspace.shared.notificationCenter.post(name: .shouldReloadPock, object: nil)
                }
            default:
                if (isHoldingFunction) {
                    isHoldingFunction = false;
                    defaults[.hideControlStrip] = true
                    NSWorkspace.shared.notificationCenter.post(name: .shouldReloadPock, object: nil)
                }
            }
        }
```

**Comment by pigigaldi** [comment]
Introduced in the latest release! https://pock.dev

**Comment by pySilver** [comment]
@pigigaldi any idea why it might not work? I'm on the latest version, but double press of control button have no effect (I'm pretty sure nothing is binded to the same keypress)

**Comment by pySilver** [comment]
Worth mentioning that double press requires application restart (at least that was the case for me)
