### ISSUE TITLE
Allow other apps to take priority

### ISSUE THREAD

**Issue by lorenzofanchi** [pigigaldi/Pock#59]
Would be great if it would be possible to allow other apps to take control of the Touch Bar. Right now Pock always seems to take priority.

This would work well with a system where the user could invoke Pock through a system hotkey, similar to what is suggested in #57  :)

**Comment by pigigaldi** [comment]
Introduced in the latest release! https://pock.dev
You can now double click on `ctrl` key to toggle Pock visibility.
