### ISSUE TITLE
Monterey: "x" button shows on left of touchbar after switching to Pock from control strip

### ISSUE THREAD

**Issue by 6twenty** [pigigaldi/Pock#598]
**Describe the bug**

I recently upgraded from Big Sur to Monterey. I have Pock configured to be able to toggle between Pock and the native touchbar control strip (via ctrl key double press). On Monterey, on switching back to Pock a "x" button appears on the left hand side that didn't used to show on Big Sur. Tapping the "x" button makes it disappear and Pock resumes taking up the full touchbar (but otherwise doesn't do anything).

**How to reproduce**

1. Double-press ctrl to switch from Pock to control strip
2. Double-press ctrol again to switch back to Pock from control strip
3. Observe "x" button appears on left-hand side

**Expected behavior**

The "x" button should not be there.

**Screenshots**

Touchbar after switching to control strip and back to Pock:

![image](https://user-images.githubusercontent.com/169607/181148093-09c5e91d-9143-4ad4-935f-6a1c8169ee4a.jpeg)

Touchbar after subsequently tapping the "x" button:

![image](https://user-images.githubusercontent.com/169607/181148154-1bf798f7-1ae8-46b2-adc2-f9472814e623.jpeg)

**Crashlog**

N/A

**Versions:**
 - macOS version: 12.5 (Monterey)
 - Pock version:  0.9.0-22

**Additional context**

N/A

**Comment by 6twenty** [comment]
Welp, this issue seems to have gone away on its own - after quitting and reopening Pock, the issue hasn't reappeared. I'll close the issue and re-open it if the issue comes back again.

**Comment by Ickerday** [comment]
This issue consistently reproduces for me when I use the `Advanced -> Reload Pock` from the tray icon menu. Happy to help with debugging. 

#### Versions:
- macOS Ventura (13.4.1)
- Pock 0.9.0-22
