### ISSUE TITLE
esc doesn't dismiss Spotlight/Alfred

### ISSUE THREAD

**Issue by lorenzofanchi** [pigigaldi/Pock#61]
I'm using the productivity tool [Alfred](https://www.alfredapp.com/) which, upon invocation, opens a window similar to the Spotlight window (Cmd + Space). The Pock `esc` button does not dismiss these windows, while the system `esc` does.

**Comment by hvdklauw** [comment]
Can confirm, did some testing and javascript does detect it the same as esc on the normal touchbar/keyboard.

So not sure what the difference is.

**Comment by andrewkdinh** [comment]
I'm having the same issue with Spotlight, but Pock's `esc` button also doesn't seem to work on any website with fullscreen video. I've tried in [YouTube](https://www.youtube.com), [Invidious](https://invidio.us), and [Vimeo](https://vimeo.com). The normal `esc` button works, though.

**Comment by TechieGenie** [comment]
Pock's `esc` button is not clearing the text typed in spotlight, and dismissing also not working.

**Comment by pesakitan22** [comment]
doesn't dismiss YouTube's fullscreen too

**Comment by pigigaldi** [comment]
Follow me on Twitter to stay updated on Pock new releases! 🌳 https://twitter.com/pigigaldi/status/1141968632924295168
