### ISSUE TITLE
launch at login 

### ISSUE THREAD

**Issue by etstorm** [pigigaldi/Pock#614]
For whatever reason whenever I click launch at login and close out preferences, it turns off. So Pock doesn't launch at login, I even tried adding it to the launch at login part of system preferences, and it still won't open at login. I'm running Pock on a 2018 MBP running Ventura 13.0.1. Thanks!

**Comment by szymonstanek** [comment]
Hey!
I had the same issue pock "lunch at login" button doesn't work. In my case (Ventrura 13.2 MBP M1 2020) adding in the system preferences fails to lunch at login. 

As a workaround i had to create AppleScript app that lunches Pock and add this app to lunch at login in system preferences. The workaround will be soon on my Github just in case.
