### ISSUE TITLE
sorting by most recent use

### ISSUE THREAD

**Issue by lorenzofanchi** [pigigaldi/Pock#63]
This might go against the concept of Pock being a second (mirrored) dock, but I suggest it anyway :)

Would be great for Pock to be able to sort apps by most recent use. I imagine the most recently used app would be aligned to the right of the touch bar.

**Comment by pigigaldi** [comment]
Introduced in the latest release! https://pock.dev
You can now enable the option to show only running apps.
Re-open this issue if this is not the desired behavior.
