### ISSUE TITLE
Different icon for Applications and Downloads

### ISSUE THREAD

**Issue by DefCon-007** [pigigaldi/Pock#68]
Currently the icon for both Applications and Downloads is same i.e. default folder icon, it would be great if they can be customised to something different.

**Comment by pigigaldi** [comment]
That's strange since this should already works on latest version available.
Could you provide on which version you're facing this issue and maybe a screenshot of both `Dock` and `Pock`?

**Comment by DefCon-007** [comment]
I am on the version `0.4.6`.
Dock Screenshot:
<img width="1155" alt="Screenshot 2019-05-23 at 5 02 44 PM" src="https://user-images.githubusercontent.com/16754547/58249493-ac33bf80-7d7c-11e9-9bdc-f151721d2e1c.png">
Touchbar Screenshot:
<img width="1085" alt="Touch Bar Shot 2019-05-23 at 5 02 17 PM" src="https://user-images.githubusercontent.com/16754547/58249511-b6ee5480-7d7c-11e9-8a17-0dd0b2c59bbd.png">

**Comment by pigigaldi** [comment]
I'm closing this. Feel free to re-open if you're still facing this issue with the latest release (https://pock.dev)
