### ISSUE TITLE
Multiple `esc` button 

### ISSUE THREAD

**Issue by andriiginting** [pigigaldi/Pock#72]
I'm using latest version `0.4.6` and i got multiple `esc` button here after quit pock and try using it again

<img width="1085" alt="Touch Bar Shot 2019-06-07 at 11 11 17" src="https://user-images.githubusercontent.com/22597869/59080895-61d24700-8915-11e9-8783-2aedf4577847.png">

**Comment by pigigaldi** [comment]
This is normal behavior. It happens when Pock is the frontmost application. For example, this occurs when you open Pock preferences pane. 👍
