### ISSUE TITLE
esc button in the leftmost position

### ISSUE THREAD

**Issue by phanam** [pigigaldi/Pock#73]
It would be nice (if possible) to place the esc-button to the leftmost position instead of second from the left. As a programmer I don't look at the keyboard and touching the leftmost position is much easier.

Thanks for considering :) !

**Comment by drewpayment** [comment]
I noticed this behavior also. It appears you can make the circle X icon hide if you hide the control strip. I think it would be nice to be able to have some sort of control strip built into Pock so you didn't have hide it while Pock is open.

**Comment by ca-kou** [comment]
Strong agree. It's very inconvenient for vim.

**Comment by pigigaldi** [comment]
This is normal behavior if you have the `Hide Control Strip` option disabled since Pock is showed inside the system Touch Bar (like the `Expanded Control Strip` do)
