### ISSUE TITLE
Dock with play controls?

### ISSUE THREAD

**Issue by nodesocket** [pigigaldi/Pock#76]
On https://pock.dev/ it shows the following screenshot:

<img width="1085" alt="pock_preview" src="https://user-images.githubusercontent.com/523312/59824675-73ddbd80-92f7-11e9-8d90-b090fcd82188.png">

How it is possible to show the dock and audio controls though? I am only able to see the dock and ESC key.

**Comment by hvdklauw** [comment]
Go to system preferences > Extensions > Touch Bar  > Customize control strip and drag on the control strip which controls you want.

And in the Pock preferences make sure Hide control strip is unchecked.

**Comment by KevinDenys** [comment]
I don't have "Touch Bar" in my extensions menu.
![image](https://user-images.githubusercontent.com/17174443/59827772-c8099180-9339-11e9-98be-27235b7bdab1.png)

**Comment by hvdklauw** [comment]
Ah my bad that's where I found it, but you can also find it

System Preferences > Keyboard > Keyboard > Customise Touch Bar...

**Comment by nodesocket** [comment]
So I have to enabled "hide control strip" in Pock, or else it keeps disappearing, or working incorrectly showing two esc buttons, etc.

That works, but I am missing the ability to adjust brightness and volume.

**Comment by marques-p44** [comment]
Pock never shows up unless I check the "Hide Control Strip" checkbox, but then it hides all my music controls. I'm not sure how to get pock to show up.

**Comment by pigigaldi** [comment]
Instructions on how to enable Pock can now be found in README.
Thanks to #78
