### ISSUE TITLE
Can't select twitch app

### ISSUE THREAD

**Issue by jwoertink** [pigigaldi/Pock#79]
**Describe the bug**
This is a weird one, but when I tap on any app aside from the [twitch desktop app](https://www.twitch.tv/downloads) it will open that app. With the twitch app, it sort of un-selects the current app, but doesn't actually switch context.

**To Reproduce**
1. Download the twitch app
2. Open twitch app
3. Tap on some other app icon
4. Tap on twitch app icon

**Expected behavior**
Expected it to open twitch

**Screenshots**
[Here's a video](https://www.dropbox.com/s/fac6lu26ae4fymh/IMG_3636.MOV?dl=0)

**Desktop (please complete the following information):**
 - OS: macOS 10.14.5
 - Browser: Firefox, but I don't think that should matter?
 - Version: Pock 0.4.6

**Additional context**
Running latest twitch version as of this date.

**Comment by pigigaldi** [comment]
That's odd behavior. I'll download Twitch app and I'm going to investigate this asap.
