### ISSUE TITLE
Missing Icons

### ISSUE THREAD

**Issue by RichAppz** [pigigaldi/Pock#83]
**Describe the bug**

**To Reproduce**
1. Add Xcode and Xcode Beta to Tool bar
2. Open Xcode
3. Go to Pock bar and click on Xcode beta! It's not there!
4. Click on Xcode. It opens Beta

**Expected behavior**
I should be able to see both the Xcode and Xcode-Beta icons and they should perform in expected manner

**Screenshots**
![IMG_3431](https://user-images.githubusercontent.com/2961823/59908549-93630c00-9405-11e9-8bd1-6b510ef0887f.JPG)

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser Safari
 - Version 10.14.5

**Comment by pigigaldi** [comment]
Hi! 
Well, I can replicate this issue but I need some time to investigate it.
Thanks for pointing this out!
