### ISSUE TITLE
brew support

### ISSUE THREAD

**Issue by FernandoMiguel** [pigigaldi/Pock#85]
add brew formula to simplify install

**Comment by matthewcmckenna** [comment]
this exists. `brew cask install pock`

**Comment by FernandoMiguel** [comment]
I did search for it, but brew returned no formula.
Thanks for pointing it out

**Comment by lorenzofanchi** [comment]
the brew cask is outdated!

**Comment by FernandoMiguel** [comment]
You can send a pr to cask with the new version and sha signature.
I do it for many apps I use, but am currently on mobile

--
Fernando Miguel

**Comment by InnovativeInventor** [comment]
@lorenzofanchi @FernandoMiguel I just submitted a pull request to update it.

**Comment by mautz-et-tong** [comment]
Came here by search: `brew install --cask pock` it is now and maybe you could update the README?
