### ISSUE TITLE
How to Open Preferences?

### ISSUE THREAD

**Issue by jeremyjh** [pigigaldi/Pock#88]
Sorry for asking such a basic question, but I cannot figure it out. I downloaded Pock from the website today. When I launch Pock it displays the dock on my touchbar and everything there works. However, I do not see any way to access Pock's preferences; after launching Pock the Finder still has the focus. No pock icon is displayed on the touchbar or on alt-tab, so I'm not able to switch to the context where a preferences menu would be available. Re-running the Pock app changes nothing.

**Comment by jeremyjh** [comment]
Doh just saw it on the status widget, sorry.

**Comment by guimello** [comment]
> Doh just saw it on the status widget, sorry.

Hi, I have the same issue. Just can't find a way to open preferences or widget settings. Can you tell me where you found it?

**Comment by jeremyjh** [comment]
@guimello when you launch it a new icon should appear on the status bar at the very top of the screen.

**Comment by guimello** [comment]
> @guimello when you launch it a new icon should appear on the status bar at the very top of the screen.

Holy moly! I didn't know this bar was called "status bar". I've been using macs for 10 years :)

Thank you @jeremyjh

**Comment by jeremyjh** [comment]
Probably its not properly called that - I think the proper term is menu bar actually.

**Comment by akajulie** [comment]
>when you launch it a new icon should appear on the status bar at the very top of the screen.

I feel this needs to be added to the README file. I spent at least 30 mins trying to figure this out.
