### ISSUE TITLE
Double ESC appearing and still no Launch at Login

### ISSUE THREAD

**Issue by pock66** [pigigaldi/Pock#89]
**Describe the bug**
when choosing Customise and dragging ESC to the bar, two occasionally appear on the left side. I have to drag the default set back to fix it.

Launch at login still not working.

The Good: love the new feature sets especially Opens Finder and Directories inside Pock.

FANTASTIC WORK

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by lorenzofanchi** [comment]
Another way to trigger this is:
1. Access Preferences from the menu bar
2. Done

**Comment by pigigaldi** [comment]
Explanation of this can be found here https://github.com/pigigaldi/Pock/issues/94#issuecomment-504774806
