### ISSUE TITLE
How to change itunes with spotify

### ISSUE THREAD

**Issue by willyarisky** [pigigaldi/Pock#92]
I can't use Spotify media control on pock, any advice to change the itunes with spotify?

http://prnt.sc/o5kx6e

**Comment by pigigaldi** [comment]
Pock uses private Apple’s MediaRemote framework for retrieving media information, so it already works with any media apps. 
It also works with Safari if any video/audio is currently playing. 
Just drag the ”Now playing” widget into Touch Bar and start playing anything you want! 👌

**Comment by TheLastProject** [comment]
It wouldn't be possible to set what app will start playing music when tapped if nothing is playing? This defaults to iTunes now despite me never using iTunes. I think that may be what OP wants (it's what I want at least).

Thank you for Pock by the way, it's great!
